import type { AppLanguage } from "@/lib/i18n/languages";

const es = {
  navToday: "Hoy",
  navAreas: "Áreas de vida",
  navMoney: "Dinero",
  navOrders: "Pedidos",
  navSubs: "Suscripciones",
  navAlerts: "Alertas",
  navSettings: "Configuración",
  askLabel: "Pregunta a Donexto",
  askPlaceholder: "¿Qué hay en mi correo sobre pedidos o pagos?",
  askSubmit: "Preguntar",
  askMic: "Dictar pregunta",
  askNoSpeech: "Este navegador no tiene dictado. Escribe la pregunta.",
  askEmpty: "No hay coincidencias en tus casos ni en tu correo.",
  askResults: "Resultados en tu correo",
  greetingMorning: "Buenos días",
  greetingAfternoon: "Buenas tardes",
  greetingEvening: "Buenas noches",
  summaryEmpty: "Hoy no hay pendientes en tu correo. Donexto sigue leyendo solo lo que autorizaste.",
  summaryOne: "1 cosa necesita tu atención hoy.",
  summaryMany: "{count} cosas necesitan tu atención hoy.",
  summaryMore: "Y {count} más en tu lista.",
  askVague: "Dime qué buscar: un área (pedidos, facturas…), un remitente, una fecha o un monto como 58.47.",
  listenSummary: "Escuchar resumen",
  doNow: "Haz esto ahora",
  sortedBy: "Ordenado por urgencia",
  moreWeek: "+{count} más esta semana",
  remind: "Recordarme",
  listen: "Escuchar",
  done: "Marcar como hecho",
  snooze: "Posponer",
  openCase: "Abrir",
  snoozeHour: "En 1 hora",
  snoozeTomorrow: "Mañana a las 9:00",
  snooze3d: "En 3 días",
  snoozedUntil: "Pospuesto hasta {when}",
  areas: "Áreas de vida",
  all: "Todo",
  moreAreas: "+{count} áreas",
  lessAreas: "Menos áreas",
  monthTitle: "Este mes en tu correo",
  monthNote: "Movimientos identificados · no es un saldo",
  monthOut: "Dinero · salidas",
  monthRefunds: "+{amount} en reembolsos · {count} movimientos",
  monthSubs: "Suscripciones · {count} activas",
  monthPer: "/ mes",
  monthIncrease: "{count} subida de precio",
  monthEmpty: "Aún no identificamos movimientos en tu correo este mes.",
  timelineEmpty: "Cuando llegue correo clasificado, cada mensaje aparece aquí en una línea.",
  loading: "Leyendo tu correo…",
  loadError: "No pudimos cargar tus casos.",
  mailboxConnected: "{provider} conectado",
  mailboxMissing: "Sin buzón conectado",
  mailboxSync: "Sincronizado",
  readOnly: "Acceso de solo lectura",
  connect: "Conectar buzón",
  refreshMail: "Traer correo nuevo",
  openInbox: "Abrir correos",
  importMail: "Importar correo",
  signOut: "Cerrar sesión",
  account: "Cuenta",
  emptyTitle: "Todavía no hay casos en esta vista",
  emptyBody: "Donexto solo lee el correo que autorizaste. No consulta bancos ni tiendas por fuera.",
  emptyConnect: "Conecta el buzón para empezar",
  filtersOpen: "Abiertos",
  filtersDone: "Hechos",
  filtersAll: "Todos",
  filtersHigh: "Urgentes",
  caseBack: "Volver",
  caseOneLine: "En una línea",
  caseSources: "Correos de este caso",
  caseEvents: "Qué pasó",
  caseNext: "Siguiente paso",
  caseReadOnly: "Solo lectura desde tu correo",
  caseOpenMail: "Ver correo",
  caseReconciled: "Conciliado con otro correo",
  caseNotBalance: "Esto sale de tu correo. No es un saldo bancario.",
  caseQuotesTitle: "Lo que dice el correo",
  caseQuotesNote: "Texto exacto del correo, sin cambios.",
  caseQuotesOpen: "Ver correo completo",
  settingsCrumb: "Configuración",
  settingsTitle: "Apariencia y accesibilidad",
  settingsHelp: "Ajusta Donexto a cómo ves, lees y escuchas. Los cambios se aplican al instante y se guardan en tu cuenta.",
  tabAccount: "Cuenta",
  tabMail: "Correo",
  tabNotifications: "Notificaciones",
  tabAppearance: "Apariencia",
  tabPrivacy: "Privacidad",
  tabAlerts: "Reglas",
  themeTitle: "Tema",
  themeNucleo: "Núcleo IA",
  themeNucleoHint: "Brillo y cristal",
  themeClaro: "Núcleo IA · Claro",
  themeClaroHint: "Luz y cristal",
  themeCommand: "Centro de mando oscuro",
  themeCommandHint: "Grafito",
  themeDay: "Día",
  themeDayHint: "Claro",
  themeDefault: "Predeterminado",
  reading: "Lectura",
  textSize: "Tamaño de texto",
  textSizeHelp: "Agranda todo el texto sin cortar contenido.",
  contrast: "Alto contraste",
  contrastHelp: "Bordes marcados, texto más brillante y sin efectos de cristal.",
  motion: "Reducir animaciones",
  motionHelp: "Sin brillos animados, flotación ni destellos.",
  voiceTitle: "Voz y lector de pantalla",
  screenReader: "Lector de pantalla optimizado",
  screenReaderHelp: "Etiquetas completas, orden de lectura lógico y aviso de cada cambio.",
  readAloud: "Leer en voz alta",
  readAloudHelp: "Cada enunciado tiene un botón Escuchar. Usa la voz de tu navegador, gratis.",
  voicePreview: "Probar voz",
  voiceSample: "Hola, soy la voz de Donexto. Así sonarán tus enunciados.",
  alertsAudio: "Avisos y audio",
  soundNote: "Nada depende solo del sonido",
  visualAlerts: "Avisos visuales",
  visualHelp: "Insignias, destello y vibración en el móvil.",
  badges: "Insignias",
  flash: "Destello",
  vibrateOpt: "Vibración",
  captions: "Subtítulos y transcripción",
  captionsHelp: "Para cualquier audio: subtítulos en vivo y transcripción completa.",
  subtitles: "Subtítulos",
  transcript: "Transcripción",
  sound: "Sonido de alerta",
  soundHelp: "Un tono breve del robot cuando Donexto tiene un aviso y la app está abierta.",
  volume: "Volumen",
  previewSound: "Probar sonido",
  guideTitle: "Asistente guía (robot)",
  guideHelp: "Nexto explica cada opción al pasar el cursor o el foco, con botón Escuchar.",
  yes: "Sí",
  no: "No",
  reset: "Restablecer valores",
  a11yNote: "Diseñado para cumplir WCAG 2.2 AA",
  keyboardNote: "Todo se puede usar con teclado · pulsa ? para ver los atajos",
  shortcutsTitle: "Atajos",
  shortcutSearch: "Buscar en tu correo",
  shortcutClose: "Cerrar o detener la voz",
  notifTitle: "Notificaciones en este dispositivo",
  notifHelp: "Donexto avisa de casos y reglas. Puedes activarlas ahora o más tarde.",
  enable: "Activar notificaciones",
  test: "Enviar aviso de prueba",
  testing: "Enviando…",
  devices: "Dispositivos",
  thisDevice: "Este dispositivo",
  noDevices: "Ningún dispositivo tiene notificaciones activas.",
  removeDevice: "Quitar",
  reopenGuide: "Volver a ver la guía",
  unsupported: "Este navegador no ofrece notificaciones web.",
  permissionDenied: "Las notificaciones están bloqueadas. Sigue los pasos de tu sistema.",
  vapidMissing: "El servidor todavía no tiene llaves VAPID. El aviso de prueba sonó dentro de la app.",
  testSent: "Enviamos el aviso de prueba.",
  skip: "Ahora no",
  later: "Lo haré después",
  onboardKicker: "Un paso, y listo",
  onboardTitle: "¿Activamos los avisos de Donexto en este dispositivo?",
  onboardBody: "Así te enteras cuando un correo se vuelve un caso. Donexto no lee bancos ni tiendas: solo el buzón que autorizaste.",
  iosInstallTitle: "En iPhone y iPad, primero instala Donexto",
  iosInstallSteps: "1. Pulsa Compartir en Safari.\n2. Elige Agregar a inicio.\n3. Abre Donexto desde el icono de la pantalla de inicio.\n4. Vuelve aquí y pulsa Activar notificaciones.",
  iosSettingsSteps: "Si ya lo instalaste y el permiso quedó bloqueado: Ajustes → Notificaciones → Donexto → Permitir notificaciones.",
  androidSteps: "1. Pulsa Activar notificaciones y elige Permitir.\n2. Si quedó bloqueado: toca el candado en la barra de Chrome → Permisos → Notificaciones → Permitir.\n3. También puedes ir a Ajustes de Android → Apps → Chrome → Notificaciones.",
  desktopSteps: "1. Pulsa Activar notificaciones y elige Permitir en el navegador.\n2. Si está bloqueado, abre el candado junto a la dirección y cambia Notificaciones a Permitir.\n3. En el sistema, revisa que el navegador pueda mostrar avisos.",
  platformIos: "iPhone o iPad",
  platformAndroid: "Android",
  platformMac: "Mac",
  platformWindows: "Windows",
  platformLinux: "Linux",
  platformDesktop: "Computadora",
  rulesTitle: "Reglas de alerta",
  rulesHelp: "Avísame cuando un correo coincida. La regla se guarda en tu cuenta.",
  ruleSender: "Remitente",
  ruleCase: "Tipo de caso",
  ruleSubject: "Asunto",
  ruleConcept: "Concepto",
  ruleValue: "Texto a vigilar",
  ruleAdd: "Guardar regla",
  ruleEmpty: "Todavía no hay reglas. Agrega una por remitente, tipo, asunto o concepto.",
  ruleRemove: "Eliminar regla",
  privacyTitle: "Qué lee Donexto",
  privacyBody: "Donexto solo lee el correo que autorizaste, en modo bandeja. Convierte esos correos en acontecimientos por área de vida. El dinero es inteligencia del correo: movimientos identificados, nunca un saldo. No hay conexión directa a tu banco ni a Amazon. Salud y familia se muestran sin diagnosticar.",
  accountEmail: "Correo de la cuenta",
  language: "Idioma",
  planTitle: "Plan Normal",
  planBody: "Outlook y Hotmail en Donexto. Prueba de Stripe a $19.99 / mes.",
  planCta: "Contratar Plan Normal $19.99",
  planBusy: "Abriendo Stripe Test…",
  bannerYahooTitle: "Yahoo con contraseña de app",
  bannerYahooBody: "Conexión directa con Yahoo mediante contraseña de app, en espera de la autorización oficial de Yahoo. Solo lectura y revocable cuando quieras.",
  bannerGmailTitle: "Gmail en acceso anticipado",
  bannerGmailBody: "Google puede decir que no ha verificado esta app. Toca Avanzado y luego Ir a Donexto. Solo lectura, revocable en myaccount.google.com/permissions. Cupo de 100 usuarios.",
  bannerImportTitle: "Importa tu correo",
  bannerImportBody: "Hace falta la primera descarga para convertir correos en casos.",
  bannerImportCta: "Empezar importación",
  searchClear: "Limpiar búsqueda",
  mailSyncRunning: "Buscando correo nuevo…",
  mailSyncProgress: "{count} descargados hasta ahora",
  mailSyncNone: "Listo: no hay correos nuevos.",
  mailSyncOne: "Listo: 1 correo nuevo.",
  mailSyncMany: "Listo: {count} correos nuevos.",
  mailSyncCases: "{count} casos nuevos en tu lista.",
  mailSyncAuth: "El permiso para leer tu correo venció o fue revocado. Vuelve a conectar tu buzón.",
  mailSyncFailed: "No se pudo traer el correo nuevo. Inténtalo de nuevo en un momento.",
  mailSyncBackground: "Sigue descargando en segundo plano; tu lista se actualizará sola.",
  mailSyncReconnect: "Reconectar correo",
  topTitle: "Tus 10 pendientes principales",
  topSubtitle: "Donexto ya leyó tu correo. Esto es lo primero que conviene atender.",
  topRuleNote: "Ordenado con reglas por urgencia, fecha límite e importancia (sin IA).",
  topEmpty: "No encontramos pendientes abiertos. ¡Vas al día!",
  topOpen: "Abrir",
  topNoDue: "Sin fecha límite",
  topDue: "Vence {date}",
  topOverdue: "Venció {date}",
  topDismiss: "Entendido",
  topLater: "Puedes volver a verlos desde Hoy › «Ver mis 10 pendientes».",
  topCta: "Ver mis 10 pendientes",
  topReasonOverdue: "Atrasado",
  topReasonToday: "Vence hoy",
  topReasonTomorrow: "Vence mañana",
  topReasonWeek: "Esta semana",
  topReasonSecurity: "Seguridad",
  topReasonMoney: "Dinero",
  topReasonPriority: "Importante",
  topReasonRecent: "Reciente",
  statusNew: "Nuevo",
  statusAnalyzing: "Analizando",
  statusInProgress: "En curso",
  statusWaiting: "En espera",
  statusDelegated: "Delegado",
  statusResolved: "Hecho",
  statusClosed: "Cerrado",
  subjectLabel: "Asunto original",
  headlineNote: "Explicación automática con reglas a partir del correo; el asunto original va debajo.",
  askHelpTitle: "Cómo hacerlo en Donexto",
  askCasesTitle: "En tus casos",
  guideDragHint: "Arrástrame encima de cualquier opción y te explico qué es. Con el teclado: flechas para moverme, Inicio para regresar a mi lugar.",
  guideNothing: "Aquí no hay una opción que explicar. Suéltame encima de un botón, una tarjeta o un área.",
  urgentHigh: "Urgente",
  urgentMed: "Pronto",
  urgentLow: "Cuando puedas",
  noDue: "Sin fecha límite",
  reconciled: "Conciliado",
  youQuestion: "¿Fuiste tú?",
  monthMoves: "{count} movimientos",
  activeSubs: "{count} activas",
  guideName: "Nexto · asistente guía",
  close: "Cerrar",
  menu: "Menú",
  alertsEmpty: "No hay alertas abiertas.",
  doneSaved: "Caso marcado como hecho.",
  caseReopen: "Reabrir",
  caseReopened: "Caso reabierto.",
  caseUndo: "Deshacer",
  caseRetry: "Reintentar",
  caseErrDone: "No se pudo marcar como hecho.",
  caseErrSnooze: "No se pudo posponer.",
  caseErrReopen: "No se pudo reabrir.",
  caseErrLocked: "El servidor tiene los cambios en pausa por mantenimiento; tu caso no cambió.",
  caseErrSession: "Tu sesión venció. Vuelve a iniciar sesión e inténtalo de nuevo.",
  caseErrMissing: "Ese caso ya no existe o no es de tu cuenta.",
  caseErrInvalid: "La fecha elegida no es válida.",
  caseErrNetwork: "Sin conexión con Donexto. Revisa tu internet.",
  caseErrGeneric: "Algo falló en el servidor. Inténtalo de nuevo.",
  actionFallback: "Revisa este correo y decide el siguiente paso.",
  previewBadge: "Vista de diseño · datos de ejemplo",
  captionsLive: "Subtítulos",
  helpAsk: "Escribe o dicta una pregunta. Donexto busca en tus casos y correos. No usa un modelo de pago.",
  helpDoNow: "Aquí va lo más urgente de tu correo, ordenado por fecha límite y prioridad.",
  helpAreas: "Cada correo cae en un área de tu vida. Elige una para ver solo esos casos.",
  helpMonth: "Un resumen de movimientos identificados en tu correo. No es un saldo.",
  helpGuide: "Nexto explica la opción que tienes bajo el cursor o el foco.",
  helpSound: "Reproduce el tono del robot. La mayoría de navegadores no usa este archivo como sonido del aviso del sistema.",
  saved: "Guardado en tu cuenta",
  errorGeneric: "No fue posible completar la acción.",
  personal: "Personal",
  connectedNow: "En línea",
  dueIn: "Vence {when}",
  overdue: "Vencido",
  openAll: "Ver todos",
  statusOpen: "Abierto",
  mailReadOnly: "El buzón se lee; Donexto no envía ni borra correos.",
  rulePlaceholder: "Ejemplo: facturas de CFE",
  onboardingPlatform: "Detectamos: {platform}",
  installed: "Instalada en la pantalla de inicio",
  notInstalled: "Abierta en el navegador",
  allowAndTest: "Activar y probar",
  flashLive: "Nuevo aviso de Donexto",
  noAmount: "Sin monto en el correo",
  ordersEmpty: "No hay pedidos en tu correo.",
  subsEmpty: "No hay suscripciones identificadas.",
  moneyEmpty: "No hay movimientos de dinero en tu correo.",
  areaCount: "{count}",
  sourcesCount: "{count} correos",
  keyboardHelp: "Atajos de teclado",
  actionToday: "Requiere acción hoy",
  actionTodayEmpty: "Nada urgente hoy. Te avisamos si llega algo a tu correo.",
  upcomingTitle: "Próximos vencimientos",
  upcomingNote: "Próximos 7 días",
  upcomingEmpty: "Sin vencimientos en los próximos 7 días.",
  dayToday: "Hoy",
  dayTomorrow: "Mañana",
  dayOverdue: "Vencido",
  alertsRecent: "Alertas recientes",
  alertsRecentEmpty: "Sin alertas en los últimos 7 días.",
  alertWhySecurity: "Seguridad",
  alertWhyPriority: "Prioridad alta",
  alertWhyPrice: "Subió de precio",
  alertWhyRule: "Tu regla",
  alertWhyPush: "Aviso",
  areasHint: "Toca un área para filtrar",
  areaOpen: "{count} abiertos",
  areaNone: "Sin pendientes",
  areaNext: "Próximo: {when}",
  areaDueSoon: "{count} vencen en 7 días",
  moneyTile: "{count} movimientos identificados en tu correo",
  moneyTileEmpty: "Sin movimientos identificados en tu correo",
  moneyNotBalance: "No es un saldo ni un estado de cuenta",
  ordersTransit: "{count} en camino",
  ordersDelivered: "{count} entregados",
  orderConfirmed: "Confirmado",
  orderShipped: "Enviado",
  orderDelivered: "Entregado",
  orderCancelled: "Cancelado",
  orderRefunded: "Reembolsado",
  subsRenew: "{count} renuevan en 7 días",
  subsIncrease: "{count} subieron de precio",
  healthInfo: "Solo informativo · no es un diagnóstico",
  askLocalNote: "Busqué en tus casos, aquí mismo, sin IA de pago.",
  askFilters: "Filtré por: {filters}",
  askTimeToday: "hoy",
  askTimeTomorrow: "mañana",
  askTimeWeek: "próximos 7 días",
  askTimeOverdue: "vencidos",
  askTimeMonth: "este mes",
  askStatusOpen: "pendientes",
  askStatusDone: "resueltos",
  askCount: "{count} resultados",
  askCountOne: "1 resultado",
  moreCount: "+{count} más",
  viewAll: "Ver todo",
  clearFilter: "Quitar filtro",
  areaMoney: "Dinero",
  areaOrders: "Pedidos",
  areaSubscriptions: "Suscripciones",
  areaWork: "Trabajo y negocios",
  areaHome: "Hogar y familia",
  areaHealth: "Salud",
  areaBills: "Facturas y vencimientos",
  areaTravel: "Viajes",
  areaSecurity: "Seguridad",
  areaGovernment: "Gobierno e impuestos",
  areaInsurance: "Seguros",
  areaEducation: "Educación",
  areaSocial: "Social",
  areaEvents: "Eventos",
  areaPromos: "Promociones",
  areaOther: "Otros",
  commandCenter: "Centro de mando",
};

export type NxKey = keyof typeof es;

const en: Record<NxKey, string> = {
  navToday: "Today",
  navAreas: "Life areas",
  navMoney: "Money",
  navOrders: "Orders",
  navSubs: "Subscriptions",
  navAlerts: "Alerts",
  navSettings: "Settings",
  askLabel: "Ask Donexto",
  askPlaceholder: "What is in my mail about orders or payments?",
  askSubmit: "Ask",
  askMic: "Dictate a question",
  askNoSpeech: "This browser has no dictation. Type the question.",
  askEmpty: "No matches in your cases or mail.",
  askResults: "Results in your mail",
  greetingMorning: "Good morning",
  greetingAfternoon: "Good afternoon",
  greetingEvening: "Good evening",
  summaryEmpty: "Nothing needs you today. Donexto only reads mail you authorized.",
  summaryOne: "1 thing needs your attention today.",
  summaryMany: "{count} things need your attention today.",
  summaryMore: "And {count} more on your list.",
  askVague: "Tell me what to look for: an area (orders, bills…), a sender, a date or an amount like 58.47.",
  listenSummary: "Listen to summary",
  doNow: "Do this now",
  sortedBy: "Sorted by urgency",
  moreWeek: "+{count} more this week",
  remind: "Remind me",
  listen: "Listen",
  done: "Mark done",
  snooze: "Snooze",
  openCase: "Open",
  snoozeHour: "In 1 hour",
  snoozeTomorrow: "Tomorrow at 9:00",
  snooze3d: "In 3 days",
  snoozedUntil: "Snoozed until {when}",
  areas: "Life areas",
  all: "All",
  moreAreas: "+{count} areas",
  lessAreas: "Fewer areas",
  monthTitle: "This month in your mail",
  monthNote: "Movements found in mail · not a balance",
  monthOut: "Money · outflows",
  monthRefunds: "+{amount} in refunds · {count} movements",
  monthSubs: "Subscriptions · {count} active",
  monthPer: "/ month",
  monthIncrease: "{count} price increase",
  monthEmpty: "No money movements identified in your mail this month.",
  timelineEmpty: "Classified mail shows up here, one line each.",
  loading: "Reading your mail…",
  loadError: "We could not load your cases.",
  mailboxConnected: "{provider} connected",
  mailboxMissing: "No mailbox connected",
  mailboxSync: "Synced",
  readOnly: "Read-only access",
  connect: "Connect mailbox",
  refreshMail: "Fetch new mail",
  openInbox: "Open mail",
  importMail: "Import mail",
  signOut: "Sign out",
  account: "Account",
  emptyTitle: "No cases in this view yet",
  emptyBody: "Donexto only reads mail you authorized. It does not call your bank or stores.",
  emptyConnect: "Connect a mailbox to start",
  filtersOpen: "Open",
  filtersDone: "Done",
  filtersAll: "All",
  filtersHigh: "Urgent",
  caseBack: "Back",
  caseOneLine: "In one line",
  caseSources: "Mail in this case",
  caseEvents: "What happened",
  caseNext: "Next step",
  caseReadOnly: "Read-only from your mail",
  caseOpenMail: "View mail",
  caseReconciled: "Matched with another email",
  caseNotBalance: "This comes from your mail. It is not a bank balance.",
  caseQuotesTitle: "What the email says",
  caseQuotesNote: "Exact text from the email, unchanged.",
  caseQuotesOpen: "View full email",
  settingsCrumb: "Settings",
  settingsTitle: "Appearance and accessibility",
  settingsHelp: "Tune how you see, read, and hear Donexto. Changes apply at once and are saved to your account.",
  tabAccount: "Account",
  tabMail: "Mail",
  tabNotifications: "Notifications",
  tabAppearance: "Appearance",
  tabPrivacy: "Privacy",
  tabAlerts: "Rules",
  themeTitle: "Theme",
  themeNucleo: "AI Core",
  themeNucleoHint: "Glow and glass",
  themeClaro: "AI Core · Light",
  themeClaroHint: "Light and glass",
  themeCommand: "Dark command center",
  themeCommandHint: "Graphite",
  themeDay: "Day",
  themeDayHint: "Light",
  themeDefault: "Default",
  reading: "Reading",
  textSize: "Text size",
  textSizeHelp: "Enlarge all text without clipping content.",
  contrast: "High contrast",
  contrastHelp: "Strong borders, brighter text, no glass effects.",
  motion: "Reduce motion",
  motionHelp: "No animated glow, float, or shimmer.",
  voiceTitle: "Voice and screen reader",
  screenReader: "Screen reader optimized",
  screenReaderHelp: "Full labels, a logical reading order, and an announcement for each change.",
  readAloud: "Read aloud",
  readAloudHelp: "Every statement has a Listen button. It uses your browser voice, free.",
  voicePreview: "Try voice",
  voiceSample: "Hello, this is Donexto’s voice. This is how your statements sound.",
  alertsAudio: "Alerts and audio",
  soundNote: "Nothing depends on sound alone",
  visualAlerts: "Visual alerts",
  visualHelp: "Badges, a flash, and vibration on mobile.",
  badges: "Badges",
  flash: "Flash",
  vibrateOpt: "Vibration",
  captions: "Captions and transcript",
  captionsHelp: "For any audio: live captions and the full transcript.",
  subtitles: "Captions",
  transcript: "Transcript",
  sound: "Alert sound",
  soundHelp: "A short robot tone when Donexto has an alert and the app is open.",
  volume: "Volume",
  previewSound: "Preview sound",
  guideTitle: "Guide assistant (robot)",
  guideHelp: "Nexto explains each option on hover or focus, with a Listen button.",
  yes: "Yes",
  no: "No",
  reset: "Reset",
  a11yNote: "Designed for WCAG 2.2 AA",
  keyboardNote: "Everything works from the keyboard · press ? for shortcuts",
  shortcutsTitle: "Shortcuts",
  shortcutSearch: "Search your mail",
  shortcutClose: "Close or stop speech",
  notifTitle: "Notifications on this device",
  notifHelp: "Donexto can alert you about cases and rules. Turn them on now or later.",
  enable: "Enable notifications",
  test: "Send a test alert",
  testing: "Sending…",
  devices: "Devices",
  thisDevice: "This device",
  noDevices: "No device has notifications on.",
  removeDevice: "Remove",
  reopenGuide: "Show the guide again",
  unsupported: "This browser does not offer web notifications.",
  permissionDenied: "Notifications are blocked. Follow the steps for your system.",
  vapidMissing: "The server does not have VAPID keys yet. The test alert played inside the app.",
  testSent: "Test alert sent.",
  skip: "Not now",
  later: "I’ll do it later",
  onboardKicker: "One step",
  onboardTitle: "Turn on Donexto alerts on this device?",
  onboardBody: "You’ll know when an email becomes a case. Donexto does not read banks or stores: only the mailbox you authorized.",
  iosInstallTitle: "On iPhone and iPad, install Donexto first",
  iosInstallSteps: "1. Tap Share in Safari.\n2. Choose Add to Home Screen.\n3. Open Donexto from the home screen icon.\n4. Come back and tap Enable notifications.",
  iosSettingsSteps: "If it is already installed and permission is blocked: Settings → Notifications → Donexto → Allow Notifications.",
  androidSteps: "1. Tap Enable notifications and choose Allow.\n2. If it was blocked: tap the lock in Chrome → Permissions → Notifications → Allow.\n3. Or open Android Settings → Apps → Chrome → Notifications.",
  desktopSteps: "1. Tap Enable notifications and choose Allow in the browser.\n2. If blocked, open the lock next to the address and set Notifications to Allow.\n3. In system settings, confirm the browser may show alerts.",
  platformIos: "iPhone or iPad",
  platformAndroid: "Android",
  platformMac: "Mac",
  platformWindows: "Windows",
  platformLinux: "Linux",
  platformDesktop: "Computer",
  rulesTitle: "Alert rules",
  rulesHelp: "Tell me when mail matches. The rule is saved on your account.",
  ruleSender: "Sender",
  ruleCase: "Case type",
  ruleSubject: "Subject",
  ruleConcept: "Concept",
  ruleValue: "Text to watch",
  ruleAdd: "Save rule",
  ruleEmpty: "No rules yet. Add one by sender, type, subject, or concept.",
  ruleRemove: "Delete rule",
  privacyTitle: "What Donexto reads",
  privacyBody: "Donexto only reads mail you authorized, inbox only. It turns those emails into life events by area. Money is mail intelligence: identified movements, never a balance. There is no direct link to your bank or Amazon. Health and family are shown without a diagnosis.",
  accountEmail: "Account email",
  language: "Language",
  planTitle: "Normal plan",
  planBody: "Outlook and Hotmail on Donexto. Stripe test at $19.99 / month.",
  planCta: "Start Normal plan $19.99",
  planBusy: "Opening Stripe Test…",
  bannerYahooTitle: "Yahoo with an app password",
  bannerYahooBody: "Direct Yahoo connection with an app password, while Yahoo’s official permission is pending. Read-only, and you can revoke it anytime.",
  bannerGmailTitle: "Gmail early access",
  bannerGmailBody: "Google may say it hasn’t verified this app. Tap Advanced, then Go to Donexto. Read-only, revocable at myaccount.google.com/permissions. Capped at 100 users.",
  bannerImportTitle: "Import your mail",
  bannerImportBody: "The first download is required before emails become cases.",
  bannerImportCta: "Start import",
  searchClear: "Clear search",
  mailSyncRunning: "Looking for new mail…",
  mailSyncProgress: "{count} downloaded so far",
  mailSyncNone: "Done: no new mail.",
  mailSyncOne: "Done: 1 new email.",
  mailSyncMany: "Done: {count} new emails.",
  mailSyncCases: "{count} new cases in your list.",
  mailSyncAuth: "The permission to read your mail expired or was revoked. Reconnect your mailbox.",
  mailSyncFailed: "New mail could not be fetched. Try again in a moment.",
  mailSyncBackground: "Still downloading in the background; your list will update on its own.",
  mailSyncReconnect: "Reconnect mail",
  topTitle: "Your top 10 to-dos",
  topSubtitle: "Donexto has read your mail. This is what to handle first.",
  topRuleNote: "Ranked with rules by urgency, due date and importance (no AI).",
  topEmpty: "No open to-dos found. You’re all caught up!",
  topOpen: "Open",
  topNoDue: "No due date",
  topDue: "Due {date}",
  topOverdue: "Was due {date}",
  topDismiss: "Got it",
  topLater: "You can see them again from Today › “See my top 10”.",
  topCta: "See my top 10",
  topReasonOverdue: "Overdue",
  topReasonToday: "Due today",
  topReasonTomorrow: "Due tomorrow",
  topReasonWeek: "This week",
  topReasonSecurity: "Security",
  topReasonMoney: "Money",
  topReasonPriority: "Important",
  topReasonRecent: "Recent",
  statusNew: "New",
  statusAnalyzing: "Analyzing",
  statusInProgress: "In progress",
  statusWaiting: "Waiting",
  statusDelegated: "Delegated",
  statusResolved: "Done",
  statusClosed: "Closed",
  subjectLabel: "Original subject",
  headlineNote: "Automatic rule-based explanation of the email; the original subject is below.",
  askHelpTitle: "How to do it in Donexto",
  askCasesTitle: "In your cases",
  guideDragHint: "Drag me over any option and I’ll explain it. Keyboard: arrow keys move me, Home puts me back.",
  guideNothing: "Nothing to explain here. Drop me on a button, a card or an area.",
  urgentHigh: "Urgent",
  urgentMed: "Soon",
  urgentLow: "When you can",
  noDue: "No deadline",
  reconciled: "Reconciled",
  youQuestion: "Was this you?",
  monthMoves: "{count} movements",
  activeSubs: "{count} active",
  guideName: "Nexto · guide",
  close: "Close",
  menu: "Menu",
  alertsEmpty: "No open alerts.",
  doneSaved: "Case marked done.",
  caseReopen: "Reopen",
  caseReopened: "Case reopened.",
  caseUndo: "Undo",
  caseRetry: "Try again",
  caseErrDone: "Couldn't mark it done.",
  caseErrSnooze: "Couldn't snooze it.",
  caseErrReopen: "Couldn't reopen it.",
  caseErrLocked: "The server has changes paused for maintenance; your case didn't change.",
  caseErrSession: "Your session expired. Sign in again and retry.",
  caseErrMissing: "That case no longer exists or isn't yours.",
  caseErrInvalid: "The chosen time isn't valid.",
  caseErrNetwork: "Can't reach Donexto. Check your connection.",
  caseErrGeneric: "Something failed on the server. Please try again.",
  actionFallback: "Review this email and choose the next step.",
  previewBadge: "Design preview · sample data",
  captionsLive: "Captions",
  helpAsk: "Type or dictate a question. Donexto searches your cases and mail. It does not call a paid model.",
  helpDoNow: "The most urgent mail, ordered by deadline and priority.",
  helpAreas: "Each email lands in a life area. Pick one to see only those cases.",
  helpMonth: "Movements identified in your mail. Not a balance.",
  helpGuide: "Nexto explains whatever is under your pointer or focus.",
  helpSound: "Plays the robot tone. Most browsers will not use this file as the system notification sound.",
  saved: "Saved to your account",
  errorGeneric: "The action could not be completed.",
  personal: "Personal",
  connectedNow: "Online",
  dueIn: "Due {when}",
  overdue: "Overdue",
  openAll: "See all",
  statusOpen: "Open",
  mailReadOnly: "The mailbox is read; Donexto does not send or delete mail.",
  rulePlaceholder: "Example: electric bills",
  onboardingPlatform: "Detected: {platform}",
  installed: "Installed on the Home Screen",
  notInstalled: "Open in the browser",
  allowAndTest: "Enable and test",
  flashLive: "New Donexto alert",
  noAmount: "No amount in the email",
  ordersEmpty: "No orders in your mail.",
  subsEmpty: "No subscriptions identified.",
  moneyEmpty: "No money movements in your mail.",
  areaCount: "{count}",
  sourcesCount: "{count} emails",
  keyboardHelp: "Keyboard shortcuts",
  actionToday: "Needs action today",
  actionTodayEmpty: "Nothing urgent today. We’ll tell you if something arrives in your mail.",
  upcomingTitle: "Coming up",
  upcomingNote: "Next 7 days",
  upcomingEmpty: "Nothing due in the next 7 days.",
  dayToday: "Today",
  dayTomorrow: "Tomorrow",
  dayOverdue: "Overdue",
  alertsRecent: "Recent alerts",
  alertsRecentEmpty: "No alerts in the last 7 days.",
  alertWhySecurity: "Security",
  alertWhyPriority: "High priority",
  alertWhyPrice: "Price went up",
  alertWhyRule: "Your rule",
  alertWhyPush: "Notice",
  areasHint: "Tap an area to filter",
  areaOpen: "{count} open",
  areaNone: "Nothing pending",
  areaNext: "Next: {when}",
  areaDueSoon: "{count} due in 7 days",
  moneyTile: "{count} movements identified in your mail",
  moneyTileEmpty: "No movements identified in your mail",
  moneyNotBalance: "Not a balance or bank statement",
  ordersTransit: "{count} on the way",
  ordersDelivered: "{count} delivered",
  orderConfirmed: "Confirmed",
  orderShipped: "Shipped",
  orderDelivered: "Delivered",
  orderCancelled: "Cancelled",
  orderRefunded: "Refunded",
  subsRenew: "{count} renew in 7 days",
  subsIncrease: "{count} went up in price",
  healthInfo: "Informational only · not a diagnosis",
  askLocalNote: "Searched your cases right here, no paid AI.",
  askFilters: "Filtered by: {filters}",
  askTimeToday: "today",
  askTimeTomorrow: "tomorrow",
  askTimeWeek: "next 7 days",
  askTimeOverdue: "overdue",
  askTimeMonth: "this month",
  askStatusOpen: "pending",
  askStatusDone: "resolved",
  askCount: "{count} results",
  askCountOne: "1 result",
  moreCount: "+{count} more",
  viewAll: "View all",
  clearFilter: "Clear filter",
  areaMoney: "Money",
  areaOrders: "Orders",
  areaSubscriptions: "Subscriptions",
  areaWork: "Work & business",
  areaHome: "Home & family",
  areaHealth: "Health",
  areaBills: "Bills & due dates",
  areaTravel: "Travel",
  areaSecurity: "Security",
  areaGovernment: "Government & taxes",
  areaInsurance: "Insurance",
  areaEducation: "Education",
  areaSocial: "Social",
  areaEvents: "Events",
  areaPromos: "Promotions",
  areaOther: "Other",
  commandCenter: "Command center",
};

const fr: Record<NxKey, string> = {
  ...en,
  navToday: "Aujourd’hui",
  navAreas: "Domaines de vie",
  navMoney: "Argent",
  navOrders: "Commandes",
  navSubs: "Abonnements",
  navAlerts: "Alertes",
  navSettings: "Réglages",
  askLabel: "Demander à Donexto",
  askPlaceholder: "Que dit mon courrier sur les commandes ou les paiements ?",
  askSubmit: "Demander",
  askMic: "Dicter une question",
  askNoSpeech: "Ce navigateur ne dicte pas. Écrivez la question.",
  askEmpty: "Aucune correspondance dans vos dossiers ni votre courrier.",
  askResults: "Résultats dans votre courrier",
  greetingMorning: "Bonjour",
  greetingAfternoon: "Bon après-midi",
  greetingEvening: "Bonsoir",
  summaryEmpty: "Rien à traiter aujourd’hui. Donexto ne lit que le courrier autorisé.",
  summaryOne: "1 chose demande votre attention aujourd’hui.",
  summaryMany: "{count} choses demandent votre attention aujourd’hui.",
  summaryMore: "Et {count} de plus dans votre liste.",
  askVague: "Dites-moi quoi chercher : un domaine (commandes, factures…), un expéditeur, une date ou un montant comme 58.47.",
  listenSummary: "Écouter le résumé",
  doNow: "À faire maintenant",
  sortedBy: "Trié par urgence",
  moreWeek: "+{count} de plus cette semaine",
  remind: "Me le rappeler",
  listen: "Écouter",
  done: "Marquer comme fait",
  snooze: "Reporter",
  openCase: "Ouvrir",
  snoozeHour: "Dans 1 heure",
  snoozeTomorrow: "Demain à 9:00",
  snooze3d: "Dans 3 jours",
  snoozedUntil: "Reporté jusqu’au {when}",
  areas: "Domaines de vie",
  all: "Tout",
  moreAreas: "+{count} domaines",
  lessAreas: "Moins de domaines",
  monthTitle: "Ce mois dans votre courrier",
  monthNote: "Mouvements repérés · ce n’est pas un solde",
  monthOut: "Argent · sorties",
  monthRefunds: "+{amount} de remboursements · {count} mouvements",
  monthSubs: "Abonnements · {count} actifs",
  monthPer: "/ mois",
  monthIncrease: "{count} hausse de prix",
  monthEmpty: "Aucun mouvement d’argent identifié dans votre courrier ce mois-ci.",
  timelineEmpty: "Le courrier classé apparaît ici, une ligne par message.",
  loading: "Lecture de votre courrier…",
  loadError: "Impossible de charger vos dossiers.",
  mailboxConnected: "{provider} connecté",
  mailboxMissing: "Aucune boîte connectée",
  mailboxSync: "Synchronisé",
  readOnly: "Accès en lecture seule",
  connect: "Connecter la boîte",
  refreshMail: "Chercher le nouveau courrier",
  openInbox: "Ouvrir le courrier",
  importMail: "Importer le courrier",
  signOut: "Se déconnecter",
  account: "Compte",
  emptyTitle: "Pas encore de dossier dans cette vue",
  emptyBody: "Donexto ne lit que le courrier autorisé. Pas de connexion à votre banque ni aux boutiques.",
  emptyConnect: "Connectez une boîte pour commencer",
  filtersOpen: "Ouverts",
  filtersDone: "Faits",
  filtersAll: "Tous",
  filtersHigh: "Urgents",
  caseBack: "Retour",
  caseOneLine: "En une ligne",
  caseSources: "Courriers de ce dossier",
  caseEvents: "Ce qui s’est passé",
  caseNext: "Étape suivante",
  caseReadOnly: "Lecture seule depuis votre courrier",
  caseOpenMail: "Voir le courrier",
  caseReconciled: "Rapproché d’un autre courrier",
  caseNotBalance: "Ceci vient de votre courrier. Ce n’est pas un solde bancaire.",
  caseQuotesTitle: "Ce que dit le courrier",
  caseQuotesNote: "Texte exact du courrier, sans modification.",
  caseQuotesOpen: "Voir le courrier complet",
  settingsCrumb: "Réglages",
  settingsTitle: "Apparence et accessibilité",
  settingsHelp: "Ajustez Donexto à votre vue, votre lecture et votre écoute. Les changements sont immédiats et enregistrés sur votre compte.",
  tabAccount: "Compte",
  tabMail: "Courrier",
  tabNotifications: "Notifications",
  tabAppearance: "Apparence",
  tabPrivacy: "Confidentialité",
  tabAlerts: "Règles",
  themeTitle: "Thème",
  themeNucleo: "Noyau IA",
  themeNucleoHint: "Lueur et verre",
  themeClaro: "Noyau IA · Clair",
  themeClaroHint: "Lumière et verre",
  themeCommand: "Centre de commande sombre",
  themeCommandHint: "Graphite",
  themeDay: "Jour",
  themeDayHint: "Clair",
  themeDefault: "Par défaut",
  reading: "Lecture",
  textSize: "Taille du texte",
  textSizeHelp: "Agrandit tout le texte sans couper le contenu.",
  contrast: "Contraste élevé",
  contrastHelp: "Bordures nettes, texte plus clair, sans effet de verre.",
  motion: "Réduire les animations",
  motionHelp: "Pas de lueur animée, de flottement ni de scintillement.",
  voiceTitle: "Voix et lecteur d’écran",
  screenReader: "Lecteur d’écran optimisé",
  screenReaderHelp: "Libellés complets, ordre de lecture logique et annonce de chaque changement.",
  readAloud: "Lire à voix haute",
  readAloudHelp: "Chaque énoncé a un bouton Écouter. La voix du navigateur est gratuite.",
  voicePreview: "Essayer la voix",
  voiceSample: "Bonjour, je suis la voix de Donexto.",
  alertsAudio: "Alertes et audio",
  soundNote: "Rien ne dépend du son seul",
  visualAlerts: "Alertes visuelles",
  visualHelp: "Badges, flash et vibration sur mobile.",
  badges: "Badges",
  flash: "Flash",
  vibrateOpt: "Vibration",
  captions: "Sous-titres et transcription",
  captionsHelp: "Pour tout audio : sous-titres en direct et transcription complète.",
  subtitles: "Sous-titres",
  transcript: "Transcription",
  sound: "Son d’alerte",
  soundHelp: "Un bref ton de robot quand Donexto a une alerte et que l’app est ouverte.",
  volume: "Volume",
  previewSound: "Essayer le son",
  guideTitle: "Assistant guide (robot)",
  guideHelp: "Nexto explique chaque option au survol ou au focus, avec un bouton Écouter.",
  yes: "Oui",
  no: "Non",
  reset: "Réinitialiser",
  a11yNote: "Conçu pour WCAG 2.2 AA",
  keyboardNote: "Tout est utilisable au clavier · appuyez sur ? pour les raccourcis",
  shortcutsTitle: "Raccourcis",
  shortcutSearch: "Chercher dans votre courrier",
  shortcutClose: "Fermer ou arrêter la voix",
  notifTitle: "Notifications sur cet appareil",
  notifHelp: "Donexto peut vous prévenir des dossiers et des règles.",
  enable: "Activer les notifications",
  test: "Envoyer une alerte test",
  testing: "Envoi…",
  devices: "Appareils",
  thisDevice: "Cet appareil",
  noDevices: "Aucun appareil n’a les notifications activées.",
  removeDevice: "Retirer",
  reopenGuide: "Revoir le guide",
  unsupported: "Ce navigateur ne propose pas les notifications web.",
  permissionDenied: "Les notifications sont bloquées. Suivez les étapes de votre système.",
  vapidMissing: "Le serveur n’a pas encore de clés VAPID. L’alerte test a joué dans l’app.",
  testSent: "Alerte test envoyée.",
  skip: "Pas maintenant",
  later: "Plus tard",
  onboardKicker: "Une étape",
  onboardTitle: "Activer les alertes Donexto sur cet appareil ?",
  onboardBody: "Vous saurez quand un courriel devient un dossier. Donexto ne lit ni banque ni boutique : seulement la boîte autorisée.",
  iosInstallTitle: "Sur iPhone et iPad, installez d’abord Donexto",
  iosInstallSteps: "1. Touchez Partager dans Safari.\n2. Choisissez Sur l’écran d’accueil.\n3. Ouvrez Donexto depuis l’icône.\n4. Revenez et touchez Activer les notifications.",
  iosSettingsSteps: "Si l’app est installée et le droit bloqué : Réglages → Notifications → Donexto → Autoriser.",
  androidSteps: "1. Touchez Activer les notifications et choisissez Autoriser.\n2. Si c’est bloqué : cadenas de Chrome → Autorisations → Notifications → Autoriser.\n3. Ou Paramètres Android → Applis → Chrome → Notifications.",
  desktopSteps: "1. Touchez Activer les notifications et choisissez Autoriser.\n2. Si c’est bloqué, ouvrez le cadenas près de l’adresse.\n3. Vérifiez aussi les notifications du système pour le navigateur.",
  platformIos: "iPhone ou iPad",
  platformAndroid: "Android",
  platformMac: "Mac",
  platformWindows: "Windows",
  platformLinux: "Linux",
  platformDesktop: "Ordinateur",
  rulesTitle: "Règles d’alerte",
  rulesHelp: "Prévenez-moi quand un courrier correspond. La règle est enregistrée sur votre compte.",
  ruleSender: "Expéditeur",
  ruleCase: "Type de dossier",
  ruleSubject: "Objet",
  ruleConcept: "Concept",
  ruleValue: "Texte à surveiller",
  ruleAdd: "Enregistrer la règle",
  ruleEmpty: "Pas encore de règle. Ajoutez-en une par expéditeur, type, objet ou concept.",
  ruleRemove: "Supprimer la règle",
  privacyTitle: "Ce que lit Donexto",
  privacyBody: "Donexto ne lit que le courrier autorisé, en boîte de réception. Il en fait des événements de vie. L’argent est une lecture du courrier : des mouvements identifiés, jamais un solde. Pas de lien direct avec votre banque ni Amazon. Santé et famille sans diagnostic.",
  accountEmail: "Courriel du compte",
  language: "Langue",
  planTitle: "Offre Normale",
  planBody: "Outlook et Hotmail dans Donexto. Essai Stripe à 19,99 $ / mois.",
  planCta: "Choisir l’offre Normale 19,99 $",
  planBusy: "Ouverture de Stripe Test…",
  bannerYahooTitle: "Yahoo avec un mot de passe d’application",
  bannerYahooBody: "Connexion directe à Yahoo avec un mot de passe d’application, en attendant l’autorisation officielle. Lecture seule, révocable quand vous voulez.",
  bannerGmailTitle: "Gmail en accès anticipé",
  bannerGmailBody: "Google peut dire qu’il n’a pas validé cette appli. Touchez Paramètres avancés, puis Accéder à Donexto. Lecture seule, révocable sur myaccount.google.com/permissions. Limite de 100 utilisateurs.",
  bannerImportTitle: "Importez votre courrier",
  bannerImportBody: "Le premier téléchargement est nécessaire pour créer des dossiers.",
  bannerImportCta: "Lancer l’import",
  searchClear: "Effacer la recherche",
  mailSyncRunning: "Recherche du nouveau courrier…",
  mailSyncProgress: "{count} téléchargés pour l’instant",
  mailSyncNone: "Terminé : aucun nouveau courrier.",
  mailSyncOne: "Terminé : 1 nouveau courriel.",
  mailSyncMany: "Terminé : {count} nouveaux courriels.",
  mailSyncCases: "{count} nouveaux dossiers dans votre liste.",
  mailSyncAuth: "L’autorisation de lire votre courrier a expiré ou a été révoquée. Reconnectez votre boîte.",
  mailSyncFailed: "Impossible de récupérer le nouveau courrier. Réessayez dans un instant.",
  mailSyncBackground: "Le téléchargement continue en arrière-plan ; votre liste se mettra à jour.",
  mailSyncReconnect: "Reconnecter",
  topTitle: "Vos 10 tâches principales",
  topSubtitle: "Donexto a lu votre courrier. Voici ce qu’il faut traiter d’abord.",
  topRuleNote: "Classé par règles : urgence, échéance et importance (sans IA).",
  topEmpty: "Aucune tâche ouverte. Vous êtes à jour !",
  topOpen: "Ouvrir",
  topNoDue: "Sans échéance",
  topDue: "Échéance {date}",
  topOverdue: "Échu le {date}",
  topDismiss: "Compris",
  topLater: "Retrouvez-les depuis Aujourd’hui › « Voir mes 10 tâches ».",
  topCta: "Voir mes 10 tâches",
  topReasonOverdue: "En retard",
  topReasonToday: "Échéance aujourd’hui",
  topReasonTomorrow: "Échéance demain",
  topReasonWeek: "Cette semaine",
  topReasonSecurity: "Sécurité",
  topReasonMoney: "Argent",
  topReasonPriority: "Important",
  topReasonRecent: "Récent",
  statusNew: "Nouveau",
  statusAnalyzing: "En analyse",
  statusInProgress: "En cours",
  statusWaiting: "En attente",
  statusDelegated: "Délégué",
  statusResolved: "Terminé",
  statusClosed: "Fermé",
  subjectLabel: "Objet d’origine",
  headlineNote: "Explication automatique par règles ; l’objet d’origine est dessous.",
  askHelpTitle: "Comment faire dans Donexto",
  askCasesTitle: "Dans vos dossiers",
  guideDragHint: "Faites-moi glisser sur une option et je l’explique. Clavier : flèches pour me déplacer, Début pour revenir.",
  guideNothing: "Rien à expliquer ici. Déposez-moi sur un bouton, une carte ou un domaine.",
  urgentHigh: "Urgent",
  urgentMed: "Bientôt",
  urgentLow: "Quand vous pouvez",
  noDue: "Sans échéance",
  reconciled: "Rapproché",
  youQuestion: "Était-ce vous ?",
  monthMoves: "{count} mouvements",
  activeSubs: "{count} actifs",
  guideName: "Nexto · guide",
  close: "Fermer",
  menu: "Menu",
  alertsEmpty: "Aucune alerte ouverte.",
  doneSaved: "Dossier marqué comme fait.",
  caseReopen: "Rouvrir",
  caseReopened: "Dossier rouvert.",
  caseUndo: "Annuler",
  caseRetry: "Réessayer",
  caseErrDone: "Impossible de le marquer comme fait.",
  caseErrSnooze: "Impossible de le reporter.",
  caseErrReopen: "Impossible de le rouvrir.",
  caseErrLocked: "Le serveur a mis les modifications en pause pour maintenance ; votre dossier n’a pas changé.",
  caseErrSession: "Votre session a expiré. Reconnectez-vous puis réessayez.",
  caseErrMissing: "Ce dossier n’existe plus ou ne vous appartient pas.",
  caseErrInvalid: "L’heure choisie n’est pas valide.",
  caseErrNetwork: "Impossible de joindre Donexto. Vérifiez votre connexion.",
  caseErrGeneric: "Une erreur est survenue sur le serveur. Réessayez.",
  actionFallback: "Relisez ce courrier et choisissez la suite.",
  previewBadge: "Aperçu de design · données d’exemple",
  captionsLive: "Sous-titres",
  helpAsk: "Écrivez ou dictez une question. Donexto cherche dans vos dossiers et courriers, sans modèle payant.",
  helpDoNow: "Le courrier le plus urgent, par échéance et priorité.",
  helpAreas: "Chaque courriel tombe dans un domaine de vie.",
  helpMonth: "Mouvements identifiés dans votre courrier. Pas un solde.",
  helpGuide: "Nexto explique l’option sous le curseur ou le focus.",
  helpSound: "Joue le ton du robot. La plupart des navigateurs ignorent ce fichier comme son système.",
  saved: "Enregistré sur votre compte",
  errorGeneric: "L’action n’a pas abouti.",
  personal: "Personnel",
  connectedNow: "En ligne",
  dueIn: "Échéance {when}",
  overdue: "En retard",
  openAll: "Tout voir",
  statusOpen: "Ouvert",
  mailReadOnly: "La boîte est lue ; Donexto n’envoie ni ne supprime de courrier.",
  rulePlaceholder: "Exemple : factures d’électricité",
  onboardingPlatform: "Détecté : {platform}",
  installed: "Installée sur l’écran d’accueil",
  notInstalled: "Ouverte dans le navigateur",
  allowAndTest: "Activer et tester",
  flashLive: "Nouvelle alerte Donexto",
  noAmount: "Pas de montant dans le courrier",
  ordersEmpty: "Aucune commande dans votre courrier.",
  subsEmpty: "Aucun abonnement identifié.",
  moneyEmpty: "Aucun mouvement d’argent dans votre courrier.",
  sourcesCount: "{count} courriers",
  keyboardHelp: "Raccourcis clavier",
  actionToday: "Action requise aujourd’hui",
  actionTodayEmpty: "Rien d’urgent aujourd’hui. Nous vous prévenons si quelque chose arrive.",
  upcomingTitle: "Échéances à venir",
  upcomingNote: "7 prochains jours",
  upcomingEmpty: "Aucune échéance dans les 7 prochains jours.",
  dayToday: "Aujourd’hui",
  dayTomorrow: "Demain",
  dayOverdue: "En retard",
  alertsRecent: "Alertes récentes",
  alertsRecentEmpty: "Aucune alerte ces 7 derniers jours.",
  alertWhySecurity: "Sécurité",
  alertWhyPriority: "Priorité haute",
  alertWhyPrice: "Prix en hausse",
  alertWhyRule: "Votre règle",
  alertWhyPush: "Avis",
  areasHint: "Touchez un domaine pour filtrer",
  areaOpen: "{count} ouverts",
  areaNone: "Rien en attente",
  areaNext: "Prochain : {when}",
  areaDueSoon: "{count} à échéance sous 7 jours",
  moneyTile: "{count} mouvements identifiés dans votre courrier",
  moneyTileEmpty: "Aucun mouvement identifié dans votre courrier",
  moneyNotBalance: "Ni un solde ni un relevé bancaire",
  ordersTransit: "{count} en route",
  ordersDelivered: "{count} livrées",
  orderConfirmed: "Confirmée",
  orderShipped: "Expédiée",
  orderDelivered: "Livrée",
  orderCancelled: "Annulée",
  orderRefunded: "Remboursée",
  subsRenew: "{count} se renouvellent sous 7 jours",
  subsIncrease: "{count} en hausse de prix",
  healthInfo: "À titre informatif · pas un diagnostic",
  askLocalNote: "Recherche dans vos dossiers, ici même, sans IA payante.",
  askFilters: "Filtré par : {filters}",
  askTimeToday: "aujourd’hui",
  askTimeTomorrow: "demain",
  askTimeWeek: "7 prochains jours",
  askTimeOverdue: "en retard",
  askTimeMonth: "ce mois-ci",
  askStatusOpen: "en attente",
  askStatusDone: "résolus",
  askCount: "{count} résultats",
  askCountOne: "1 résultat",
  moreCount: "+{count} de plus",
  viewAll: "Tout voir",
  clearFilter: "Retirer le filtre",
  areaMoney: "Argent",
  areaOrders: "Commandes",
  areaSubscriptions: "Abonnements",
  areaWork: "Travail et affaires",
  areaHome: "Foyer et famille",
  areaHealth: "Santé",
  areaBills: "Factures et échéances",
  areaTravel: "Voyages",
  areaSecurity: "Sécurité",
  areaGovernment: "Administration et impôts",
  areaInsurance: "Assurances",
  areaEducation: "Éducation",
  areaSocial: "Social",
  areaEvents: "Événements",
  areaPromos: "Promotions",
  areaOther: "Autres",
  commandCenter: "Centre de commande",
};

const it: Record<NxKey, string> = {
  ...en,
  navToday: "Oggi",
  navAreas: "Aree di vita",
  navMoney: "Denaro",
  navOrders: "Ordini",
  navSubs: "Abbonamenti",
  navAlerts: "Avvisi",
  navSettings: "Impostazioni",
  askLabel: "Chiedi a Donexto",
  askPlaceholder: "Cosa c’è nella posta su ordini o pagamenti?",
  askSubmit: "Chiedi",
  askMic: "Detta una domanda",
  askNoSpeech: "Questo browser non detta. Scrivi la domanda.",
  askEmpty: "Nessuna corrispondenza nei casi o nella posta.",
  askResults: "Risultati nella posta",
  greetingMorning: "Buongiorno",
  greetingAfternoon: "Buon pomeriggio",
  greetingEvening: "Buonasera",
  summaryEmpty: "Oggi non c’è nulla in sospeso. Donexto legge solo la posta autorizzata.",
  summaryOne: "1 cosa richiede attenzione oggi.",
  summaryMany: "{count} cose richiedono attenzione oggi.",
  summaryMore: "E altre {count} nella tua lista.",
  askVague: "Dimmi cosa cercare: un’area (ordini, bollette…), un mittente, una data o un importo come 58.47.",
  listenSummary: "Ascolta il riepilogo",
  doNow: "Fallo ora",
  sortedBy: "Per urgenza",
  moreWeek: "+{count} questa settimana",
  remind: "Ricordamelo",
  listen: "Ascolta",
  done: "Segna come fatto",
  snooze: "Posticipa",
  openCase: "Apri",
  snoozeHour: "Tra 1 ora",
  snoozeTomorrow: "Domani alle 9:00",
  snooze3d: "Tra 3 giorni",
  snoozedUntil: "Posticipato fino a {when}",
  areas: "Aree di vita",
  all: "Tutto",
  moreAreas: "+{count} aree",
  lessAreas: "Meno aree",
  monthTitle: "Questo mese nella posta",
  monthNote: "Movimenti identificati · non è un saldo",
  monthOut: "Denaro · uscite",
  monthRefunds: "+{amount} di rimborsi · {count} movimenti",
  monthSubs: "Abbonamenti · {count} attivi",
  monthPer: "/ mese",
  monthIncrease: "{count} aumento di prezzo",
  monthEmpty: "Nessun movimento di denaro identificato nella posta questo mese.",
  timelineEmpty: "La posta classificata compare qui, una riga per messaggio.",
  loading: "Lettura della posta…",
  loadError: "Non è stato possibile caricare i casi.",
  mailboxConnected: "{provider} connesso",
  mailboxMissing: "Nessuna casella connessa",
  mailboxSync: "Sincronizzato",
  readOnly: "Accesso in sola lettura",
  connect: "Connetti casella",
  refreshMail: "Scarica la posta nuova",
  openInbox: "Apri la posta",
  importMail: "Importa la posta",
  signOut: "Esci",
  account: "Account",
  emptyTitle: "Nessun caso in questa vista",
  emptyBody: "Donexto legge solo la posta autorizzata. Non interroga banche né negozi.",
  emptyConnect: "Connetti una casella per iniziare",
  filtersOpen: "Aperti",
  filtersDone: "Fatti",
  filtersAll: "Tutti",
  filtersHigh: "Urgenti",
  caseBack: "Indietro",
  caseOneLine: "In una riga",
  caseSources: "Email di questo caso",
  caseEvents: "Che cosa è successo",
  caseNext: "Passo successivo",
  caseReadOnly: "Sola lettura dalla tua posta",
  caseOpenMail: "Vedi email",
  caseReconciled: "Abbinato a un’altra email",
  caseNotBalance: "Questo viene dalla posta. Non è un saldo bancario.",
  caseQuotesTitle: "Cosa dice l’email",
  caseQuotesNote: "Testo esatto dell’email, senza modifiche.",
  caseQuotesOpen: "Vedi email completa",
  settingsCrumb: "Impostazioni",
  settingsTitle: "Aspetto e accessibilità",
  settingsHelp: "Regola come vedi, leggi e ascolti Donexto. Le modifiche sono immediate e salvate sull’account.",
  tabAccount: "Account",
  tabMail: "Posta",
  tabNotifications: "Notifiche",
  tabAppearance: "Aspetto",
  tabPrivacy: "Privacy",
  tabAlerts: "Regole",
  themeTitle: "Tema",
  themeNucleo: "Nucleo IA",
  themeNucleoHint: "Luce e vetro",
  themeClaro: "Nucleo IA · Chiaro",
  themeClaroHint: "Chiaro e vetro",
  themeCommand: "Centro di comando scuro",
  themeCommandHint: "Grafite",
  themeDay: "Giorno",
  themeDayHint: "Chiaro",
  themeDefault: "Predefinito",
  reading: "Lettura",
  textSize: "Dimensione del testo",
  textSizeHelp: "Ingrandisce tutto il testo senza tagliare i contenuti.",
  contrast: "Alto contrasto",
  contrastHelp: "Bordi marcati, testo più chiaro, senza effetti vetro.",
  motion: "Riduci animazioni",
  motionHelp: "Niente bagliori, fluttuazione o scintillio.",
  voiceTitle: "Voce e lettore di schermo",
  screenReader: "Lettore di schermo ottimizzato",
  screenReaderHelp: "Etichette complete, ordine logico e annuncio di ogni modifica.",
  readAloud: "Leggi ad alta voce",
  readAloudHelp: "Ogni enunciato ha Ascolta. Usa la voce del browser, gratis.",
  voicePreview: "Prova la voce",
  voiceSample: "Ciao, sono la voce di Donexto.",
  alertsAudio: "Avvisi e audio",
  soundNote: "Niente dipende solo dal suono",
  visualAlerts: "Avvisi visivi",
  visualHelp: "Badge, flash e vibrazione sul cellulare.",
  badges: "Badge",
  flash: "Flash",
  vibrateOpt: "Vibrazione",
  captions: "Sottotitoli e trascrizione",
  captionsHelp: "Per ogni audio: sottotitoli dal vivo e trascrizione completa.",
  subtitles: "Sottotitoli",
  transcript: "Trascrizione",
  sound: "Suono di avviso",
  soundHelp: "Un breve tono del robot quando Donexto ha un avviso e l’app è aperta.",
  volume: "Volume",
  previewSound: "Prova il suono",
  guideTitle: "Assistente guida (robot)",
  guideHelp: "Nexto spiega ogni opzione al passaggio o al focus, con Ascolta.",
  yes: "Sì",
  no: "No",
  reset: "Ripristina",
  a11yNote: "Progettato per WCAG 2.2 AA",
  keyboardNote: "Tutto si usa da tastiera · premi ? per le scorciatoie",
  shortcutsTitle: "Scorciatoie",
  shortcutSearch: "Cerca nella posta",
  shortcutClose: "Chiudi o ferma la voce",
  notifTitle: "Notifiche su questo dispositivo",
  notifHelp: "Donexto può avvisarti di casi e regole.",
  enable: "Attiva le notifiche",
  test: "Invia un avviso di prova",
  testing: "Invio…",
  devices: "Dispositivi",
  thisDevice: "Questo dispositivo",
  noDevices: "Nessun dispositivo ha le notifiche attive.",
  removeDevice: "Rimuovi",
  reopenGuide: "Rivedi la guida",
  unsupported: "Questo browser non offre notifiche web.",
  permissionDenied: "Le notifiche sono bloccate. Segui i passi del sistema.",
  vapidMissing: "Il server non ha ancora chiavi VAPID. L’avviso di prova è suonato nell’app.",
  testSent: "Avviso di prova inviato.",
  skip: "Non ora",
  later: "Più tardi",
  onboardKicker: "Un passo",
  onboardTitle: "Attiviamo gli avvisi Donexto su questo dispositivo?",
  onboardBody: "Saprai quando un’email diventa un caso. Donexto non legge banche né negozi: solo la casella autorizzata.",
  iosInstallTitle: "Su iPhone e iPad, installa prima Donexto",
  iosInstallSteps: "1. Tocca Condividi in Safari.\n2. Scegli Aggiungi a Home.\n3. Apri Donexto dall’icona.\n4. Torna qui e tocca Attiva le notifiche.",
  iosSettingsSteps: "Se è già installata e il permesso è bloccato: Impostazioni → Notifiche → Donexto → Consenti.",
  androidSteps: "1. Tocca Attiva le notifiche e scegli Consenti.\n2. Se è bloccato: lucchetto di Chrome → Autorizzazioni → Notifiche → Consenti.\n3. Oppure Impostazioni Android → App → Chrome → Notifiche.",
  desktopSteps: "1. Tocca Attiva le notifiche e scegli Consenti.\n2. Se è bloccato, apri il lucchetto accanto all’indirizzo.\n3. Controlla anche le notifiche di sistema del browser.",
  platformIos: "iPhone o iPad",
  platformAndroid: "Android",
  platformMac: "Mac",
  platformWindows: "Windows",
  platformLinux: "Linux",
  platformDesktop: "Computer",
  rulesTitle: "Regole di avviso",
  rulesHelp: "Avvisami quando la posta coincide. La regola resta sul tuo account.",
  ruleSender: "Mittente",
  ruleCase: "Tipo di caso",
  ruleSubject: "Oggetto",
  ruleConcept: "Concetto",
  ruleValue: "Testo da seguire",
  ruleAdd: "Salva regola",
  ruleEmpty: "Nessuna regola. Aggiungine una per mittente, tipo, oggetto o concetto.",
  ruleRemove: "Elimina regola",
  privacyTitle: "Che cosa legge Donexto",
  privacyBody: "Donexto legge solo la posta autorizzata, in sola ricezione. La trasforma in eventi di vita. Il denaro è intelligenza della posta: movimenti identificati, mai un saldo. Nessun collegamento diretto a banca o Amazon. Salute e famiglia senza diagnosi.",
  accountEmail: "Email dell’account",
  language: "Lingua",
  planTitle: "Piano Normal",
  planBody: "Outlook e Hotmail in Donexto. Prova Stripe a $19.99 / mese.",
  planCta: "Attiva il piano Normal $19.99",
  planBusy: "Apertura di Stripe Test…",
  bannerYahooTitle: "Yahoo con password per l’app",
  bannerYahooBody: "Connessione diretta a Yahoo con una password per l’app, in attesa dell’autorizzazione ufficiale. Sola lettura, revocabile quando vuoi.",
  bannerGmailTitle: "Gmail in accesso anticipato",
  bannerGmailBody: "Google può dire che non ha verificato questa app. Tocca Avanzate e poi Vai a Donexto. Sola lettura, revocabile su myaccount.google.com/permissions. Limite di 100 utenti.",
  bannerImportTitle: "Importa la posta",
  bannerImportBody: "Serve il primo scaricamento per trasformare le email in casi.",
  bannerImportCta: "Avvia importazione",
  searchClear: "Cancella ricerca",
  mailSyncRunning: "Cerco la posta nuova…",
  mailSyncProgress: "{count} scaricati finora",
  mailSyncNone: "Fatto: nessuna nuova email.",
  mailSyncOne: "Fatto: 1 nuova email.",
  mailSyncMany: "Fatto: {count} nuove email.",
  mailSyncCases: "{count} nuovi casi nella tua lista.",
  mailSyncAuth: "Il permesso di leggere la posta è scaduto o è stato revocato. Ricollega la casella.",
  mailSyncFailed: "Impossibile scaricare la posta nuova. Riprova tra poco.",
  mailSyncBackground: "Il download continua in background; la lista si aggiornerà da sola.",
  mailSyncReconnect: "Ricollega",
  topTitle: "Le tue 10 cose principali",
  topSubtitle: "Donexto ha letto la tua posta. Ecco cosa conviene fare prima.",
  topRuleNote: "Ordinato con regole per urgenza, scadenza e importanza (senza IA).",
  topEmpty: "Nessuna cosa aperta. Sei in pari!",
  topOpen: "Apri",
  topNoDue: "Senza scadenza",
  topDue: "Scade {date}",
  topOverdue: "Scaduto {date}",
  topDismiss: "Ho capito",
  topLater: "Puoi rivederle da Oggi › «Vedi le mie 10 cose».",
  topCta: "Vedi le mie 10 cose",
  topReasonOverdue: "In ritardo",
  topReasonToday: "Scade oggi",
  topReasonTomorrow: "Scade domani",
  topReasonWeek: "Questa settimana",
  topReasonSecurity: "Sicurezza",
  topReasonMoney: "Denaro",
  topReasonPriority: "Importante",
  topReasonRecent: "Recente",
  statusNew: "Nuovo",
  statusAnalyzing: "In analisi",
  statusInProgress: "In corso",
  statusWaiting: "In attesa",
  statusDelegated: "Delegato",
  statusResolved: "Fatto",
  statusClosed: "Chiuso",
  subjectLabel: "Oggetto originale",
  headlineNote: "Spiegazione automatica con regole; l’oggetto originale è sotto.",
  askHelpTitle: "Come fare in Donexto",
  askCasesTitle: "Nei tuoi casi",
  guideDragHint: "Trascinami sopra un’opzione e te la spiego. Tastiera: frecce per muovermi, Home per tornare al mio posto.",
  guideNothing: "Qui non c’è nulla da spiegare. Lasciami su un pulsante, una scheda o un’area.",
  urgentHigh: "Urgente",
  urgentMed: "Presto",
  urgentLow: "Quando puoi",
  noDue: "Senza scadenza",
  reconciled: "Riconciliato",
  youQuestion: "Sei stato tu?",
  monthMoves: "{count} movimenti",
  activeSubs: "{count} attivi",
  guideName: "Nexto · guida",
  close: "Chiudi",
  menu: "Menu",
  alertsEmpty: "Nessun avviso aperto.",
  doneSaved: "Caso segnato come fatto.",
  caseReopen: "Riapri",
  caseReopened: "Pratica riaperta.",
  caseUndo: "Annulla",
  caseRetry: "Riprova",
  caseErrDone: "Impossibile segnarla come fatta.",
  caseErrSnooze: "Impossibile posticiparla.",
  caseErrReopen: "Impossibile riaprirla.",
  caseErrLocked: "Il server ha sospeso le modifiche per manutenzione; la pratica non è cambiata.",
  caseErrSession: "La sessione è scaduta. Accedi di nuovo e riprova.",
  caseErrMissing: "Questa pratica non esiste più o non è tua.",
  caseErrInvalid: "L’orario scelto non è valido.",
  caseErrNetwork: "Impossibile raggiungere Donexto. Controlla la connessione.",
  caseErrGeneric: "Errore sul server. Riprova.",
  actionFallback: "Rileggi questa email e scegli il passo successivo.",
  previewBadge: "Anteprima di design · dati di esempio",
  captionsLive: "Sottotitoli",
  helpAsk: "Scrivi o detta una domanda. Donexto cerca nei casi e nella posta, senza un modello a pagamento.",
  helpDoNow: "La posta più urgente, per scadenza e priorità.",
  helpAreas: "Ogni email cade in un’area di vita.",
  helpMonth: "Movimenti identificati nella posta. Non è un saldo.",
  helpGuide: "Nexto spiega l’opzione sotto il puntatore o il focus.",
  helpSound: "Riproduce il tono del robot. Quasi tutti i browser ignorano questo file come suono di sistema.",
  saved: "Salvato sull’account",
  errorGeneric: "Azione non completata.",
  personal: "Personale",
  connectedNow: "Online",
  dueIn: "Scade {when}",
  overdue: "Scaduto",
  openAll: "Vedi tutti",
  statusOpen: "Aperto",
  mailReadOnly: "La casella si legge; Donexto non invia né cancella posta.",
  rulePlaceholder: "Esempio: bollette della luce",
  onboardingPlatform: "Rilevato: {platform}",
  installed: "Installata nella schermata Home",
  notInstalled: "Aperta nel browser",
  allowAndTest: "Attiva e prova",
  flashLive: "Nuovo avviso Donexto",
  noAmount: "Nessun importo nell’email",
  ordersEmpty: "Nessun ordine nella posta.",
  subsEmpty: "Nessun abbonamento identificato.",
  moneyEmpty: "Nessun movimento di denaro nella posta.",
  sourcesCount: "{count} email",
  keyboardHelp: "Scorciatoie da tastiera",
  actionToday: "Richiede azione oggi",
  actionTodayEmpty: "Niente di urgente oggi. Ti avvisiamo se arriva qualcosa nella posta.",
  upcomingTitle: "Prossime scadenze",
  upcomingNote: "Prossimi 7 giorni",
  upcomingEmpty: "Nessuna scadenza nei prossimi 7 giorni.",
  dayToday: "Oggi",
  dayTomorrow: "Domani",
  dayOverdue: "Scaduto",
  alertsRecent: "Avvisi recenti",
  alertsRecentEmpty: "Nessun avviso negli ultimi 7 giorni.",
  alertWhySecurity: "Sicurezza",
  alertWhyPriority: "Priorità alta",
  alertWhyPrice: "Prezzo aumentato",
  alertWhyRule: "La tua regola",
  alertWhyPush: "Avviso",
  areasHint: "Tocca un’area per filtrare",
  areaOpen: "{count} aperti",
  areaNone: "Niente in sospeso",
  areaNext: "Prossimo: {when}",
  areaDueSoon: "{count} in scadenza entro 7 giorni",
  moneyTile: "{count} movimenti identificati nella posta",
  moneyTileEmpty: "Nessun movimento identificato nella posta",
  moneyNotBalance: "Non è un saldo né un estratto conto",
  ordersTransit: "{count} in arrivo",
  ordersDelivered: "{count} consegnati",
  orderConfirmed: "Confermato",
  orderShipped: "Spedito",
  orderDelivered: "Consegnato",
  orderCancelled: "Annullato",
  orderRefunded: "Rimborsato",
  subsRenew: "{count} si rinnovano entro 7 giorni",
  subsIncrease: "{count} con prezzo aumentato",
  healthInfo: "Solo informativo · non è una diagnosi",
  askLocalNote: "Ho cercato nei tuoi casi, qui, senza IA a pagamento.",
  askFilters: "Filtrato per: {filters}",
  askTimeToday: "oggi",
  askTimeTomorrow: "domani",
  askTimeWeek: "prossimi 7 giorni",
  askTimeOverdue: "scaduti",
  askTimeMonth: "questo mese",
  askStatusOpen: "in sospeso",
  askStatusDone: "risolti",
  askCount: "{count} risultati",
  askCountOne: "1 risultato",
  moreCount: "+{count} altri",
  viewAll: "Vedi tutto",
  clearFilter: "Rimuovi filtro",
  areaMoney: "Denaro",
  areaOrders: "Ordini",
  areaSubscriptions: "Abbonamenti",
  areaWork: "Lavoro e affari",
  areaHome: "Casa e famiglia",
  areaHealth: "Salute",
  areaBills: "Fatture e scadenze",
  areaTravel: "Viaggi",
  areaSecurity: "Sicurezza",
  areaGovernment: "Governo e tasse",
  areaInsurance: "Assicurazioni",
  areaEducation: "Istruzione",
  areaSocial: "Social",
  areaEvents: "Eventi",
  areaPromos: "Promozioni",
  areaOther: "Altro",
  commandCenter: "Centro di comando",
};

const pt: Record<NxKey, string> = {
  ...en,
  navToday: "Hoje",
  navAreas: "Áreas da vida",
  navMoney: "Dinheiro",
  navOrders: "Pedidos",
  navSubs: "Assinaturas",
  navAlerts: "Alertas",
  navSettings: "Configuração",
  askLabel: "Pergunte à Donexto",
  askPlaceholder: "O que há no meu e-mail sobre pedidos ou pagamentos?",
  askSubmit: "Perguntar",
  askMic: "Ditar pergunta",
  askNoSpeech: "Este navegador não dita. Escreva a pergunta.",
  askEmpty: "Nenhuma correspondência nos casos nem no e-mail.",
  askResults: "Resultados no seu e-mail",
  greetingMorning: "Bom dia",
  greetingAfternoon: "Boa tarde",
  greetingEvening: "Boa noite",
  summaryEmpty: "Nada pendente hoje. A Donexto só lê o e-mail que você autorizou.",
  summaryOne: "1 coisa precisa da sua atenção hoje.",
  summaryMany: "{count} coisas precisam da sua atenção hoje.",
  summaryMore: "E mais {count} na sua lista.",
  askVague: "Diga o que procurar: uma área (pedidos, contas…), um remetente, uma data ou um valor como 58.47.",
  listenSummary: "Ouvir resumo",
  doNow: "Faça isto agora",
  sortedBy: "Por urgência",
  moreWeek: "+{count} nesta semana",
  remind: "Lembrar-me",
  listen: "Ouvir",
  done: "Marcar como feito",
  snooze: "Adiar",
  openCase: "Abrir",
  snoozeHour: "Em 1 hora",
  snoozeTomorrow: "Amanhã às 9:00",
  snooze3d: "Em 3 dias",
  snoozedUntil: "Adiado até {when}",
  areas: "Áreas da vida",
  all: "Tudo",
  moreAreas: "+{count} áreas",
  lessAreas: "Menos áreas",
  monthTitle: "Este mês no seu e-mail",
  monthNote: "Movimentos identificados · não é um saldo",
  monthOut: "Dinheiro · saídas",
  monthRefunds: "+{amount} em reembolsos · {count} movimentos",
  monthSubs: "Assinaturas · {count} ativas",
  monthPer: "/ mês",
  monthIncrease: "{count} aumento de preço",
  monthEmpty: "Ainda não identificamos movimentos de dinheiro no seu e-mail neste mês.",
  timelineEmpty: "O e-mail classificado aparece aqui, uma linha por mensagem.",
  loading: "Lendo seu e-mail…",
  loadError: "Não foi possível carregar seus casos.",
  mailboxConnected: "{provider} conectado",
  mailboxMissing: "Nenhuma caixa conectada",
  mailboxSync: "Sincronizado",
  readOnly: "Acesso somente leitura",
  connect: "Conectar caixa",
  refreshMail: "Buscar e-mail novo",
  openInbox: "Abrir e-mails",
  importMail: "Importar e-mail",
  signOut: "Sair",
  account: "Conta",
  emptyTitle: "Ainda não há casos nesta vista",
  emptyBody: "A Donexto só lê o e-mail autorizado. Não consulta bancos nem lojas.",
  emptyConnect: "Conecte a caixa para começar",
  filtersOpen: "Abertos",
  filtersDone: "Feitos",
  filtersAll: "Todos",
  filtersHigh: "Urgentes",
  caseBack: "Voltar",
  caseOneLine: "Em uma linha",
  caseSources: "E-mails deste caso",
  caseEvents: "O que aconteceu",
  caseNext: "Próximo passo",
  caseReadOnly: "Somente leitura a partir do seu e-mail",
  caseOpenMail: "Ver e-mail",
  caseReconciled: "Conciliado com outro e-mail",
  caseNotBalance: "Isto vem do seu e-mail. Não é um saldo bancário.",
  caseQuotesTitle: "O que o e-mail diz",
  caseQuotesNote: "Texto exato do e-mail, sem alterações.",
  caseQuotesOpen: "Ver e-mail completo",
  settingsCrumb: "Configuração",
  settingsTitle: "Aparência e acessibilidade",
  settingsHelp: "Ajuste como você vê, lê e ouve a Donexto. As mudanças valem na hora e ficam na sua conta.",
  tabAccount: "Conta",
  tabMail: "E-mail",
  tabNotifications: "Notificações",
  tabAppearance: "Aparência",
  tabPrivacy: "Privacidade",
  tabAlerts: "Regras",
  themeTitle: "Tema",
  themeNucleo: "Núcleo IA",
  themeNucleoHint: "Brilho e vidro",
  themeClaro: "Núcleo IA · Claro",
  themeClaroHint: "Luz e vidro",
  themeCommand: "Centro de comando escuro",
  themeCommandHint: "Grafite",
  themeDay: "Dia",
  themeDayHint: "Claro",
  themeDefault: "Padrão",
  reading: "Leitura",
  textSize: "Tamanho do texto",
  textSizeHelp: "Aumenta todo o texto sem cortar o conteúdo.",
  contrast: "Alto contraste",
  contrastHelp: "Bordas fortes, texto mais claro e sem efeito de vidro.",
  motion: "Reduzir animações",
  motionHelp: "Sem brilho animado, flutuação ou cintilação.",
  voiceTitle: "Voz e leitor de tela",
  screenReader: "Leitor de tela otimizado",
  screenReaderHelp: "Rótulos completos, ordem lógica e aviso de cada mudança.",
  readAloud: "Ler em voz alta",
  readAloudHelp: "Cada enunciado tem Ouvir. Usa a voz do navegador, de graça.",
  voicePreview: "Testar voz",
  voiceSample: "Olá, esta é a voz da Donexto.",
  alertsAudio: "Avisos e áudio",
  soundNote: "Nada depende só do som",
  visualAlerts: "Avisos visuais",
  visualHelp: "Selos, flash e vibração no celular.",
  badges: "Selos",
  flash: "Flash",
  vibrateOpt: "Vibração",
  captions: "Legendas e transcrição",
  captionsHelp: "Para qualquer áudio: legendas ao vivo e a transcrição completa.",
  subtitles: "Legendas",
  transcript: "Transcrição",
  sound: "Som de alerta",
  soundHelp: "Um tom curto do robô quando a Donexto tem um aviso e o app está aberto.",
  volume: "Volume",
  previewSound: "Testar som",
  guideTitle: "Assistente guia (robô)",
  guideHelp: "O Nexto explica cada opção ao passar o cursor ou o foco, com o botão Ouvir.",
  yes: "Sim",
  no: "Não",
  reset: "Restaurar",
  a11yNote: "Feito para WCAG 2.2 AA",
  keyboardNote: "Tudo funciona pelo teclado · pressione ? para os atalhos",
  shortcutsTitle: "Atalhos",
  shortcutSearch: "Buscar no e-mail",
  shortcutClose: "Fechar ou parar a voz",
  notifTitle: "Notificações neste dispositivo",
  notifHelp: "A Donexto pode avisar sobre casos e regras.",
  enable: "Ativar notificações",
  test: "Enviar aviso de teste",
  testing: "Enviando…",
  devices: "Dispositivos",
  thisDevice: "Este dispositivo",
  noDevices: "Nenhum dispositivo tem notificações ativas.",
  removeDevice: "Remover",
  reopenGuide: "Ver o guia de novo",
  unsupported: "Este navegador não oferece notificações web.",
  permissionDenied: "As notificações estão bloqueadas. Siga os passos do sistema.",
  vapidMissing: "O servidor ainda não tem chaves VAPID. O aviso de teste tocou dentro do app.",
  testSent: "Aviso de teste enviado.",
  skip: "Agora não",
  later: "Depois",
  onboardKicker: "Um passo",
  onboardTitle: "Ativar os avisos da Donexto neste dispositivo?",
  onboardBody: "Você fica sabendo quando um e-mail vira um caso. A Donexto não lê bancos nem lojas: só a caixa que você autorizou.",
  iosInstallTitle: "No iPhone e no iPad, instale a Donexto primeiro",
  iosInstallSteps: "1. Toque em Compartilhar no Safari.\n2. Escolha Adicionar à Tela de Início.\n3. Abra a Donexto pelo ícone.\n4. Volte e toque em Ativar notificações.",
  iosSettingsSteps: "Se já instalou e o permiso ficou bloqueado: Ajustes → Notificações → Donexto → Permitir.",
  androidSteps: "1. Toque em Ativar notificações e escolha Permitir.\n2. Se ficou bloqueado: cadeado do Chrome → Permissões → Notificações → Permitir.\n3. Ou Ajustes do Android → Apps → Chrome → Notificações.",
  desktopSteps: "1. Toque em Ativar notificações e escolha Permitir.\n2. Se estiver bloqueado, abra o cadeado ao lado do endereço.\n3. Confira também as notificações do sistema para o navegador.",
  platformIos: "iPhone ou iPad",
  platformAndroid: "Android",
  platformMac: "Mac",
  platformWindows: "Windows",
  platformLinux: "Linux",
  platformDesktop: "Computador",
  rulesTitle: "Regras de alerta",
  rulesHelp: "Avise quando um e-mail coincidir. A regra fica na sua conta.",
  ruleSender: "Remetente",
  ruleCase: "Tipo de caso",
  ruleSubject: "Assunto",
  ruleConcept: "Conceito",
  ruleValue: "Texto a vigiar",
  ruleAdd: "Salvar regra",
  ruleEmpty: "Ainda não há regras. Adicione uma por remetente, tipo, assunto ou conceito.",
  ruleRemove: "Excluir regra",
  privacyTitle: "O que a Donexto lê",
  privacyBody: "A Donexto só lê o e-mail autorizado, na caixa de entrada. Transforma esses e-mails em acontecimentos por área da vida. O dinheiro é inteligência do e-mail: movimentos identificados, nunca um saldo. Não há ligação direta com banco nem Amazon. Saúde e família sem diagnóstico.",
  accountEmail: "E-mail da conta",
  language: "Idioma",
  planTitle: "Plano Normal",
  planBody: "Outlook e Hotmail na Donexto. Teste Stripe a US$ 19,99 / mês.",
  planCta: "Contratar Plano Normal US$ 19,99",
  planBusy: "Abrindo Stripe Test…",
  bannerYahooTitle: "Yahoo com senha de app",
  bannerYahooBody: "Conexão direta com o Yahoo por senha de app, enquanto a autorização oficial não chega. Somente leitura e revogável quando quiser.",
  bannerGmailTitle: "Gmail em acesso antecipado",
  bannerGmailBody: "O Google pode dizer que não verificou este app. Toque em Avançado e depois em Ir para Donexto. Somente leitura, revogável em myaccount.google.com/permissions. Limite de 100 usuários.",
  bannerImportTitle: "Importe seu e-mail",
  bannerImportBody: "A primeira descarga é necessária para transformar e-mails em casos.",
  bannerImportCta: "Começar importação",
  searchClear: "Limpar busca",
  mailSyncRunning: "Buscando e-mail novo…",
  mailSyncProgress: "{count} baixados até agora",
  mailSyncNone: "Pronto: nenhum e-mail novo.",
  mailSyncOne: "Pronto: 1 e-mail novo.",
  mailSyncMany: "Pronto: {count} e-mails novos.",
  mailSyncCases: "{count} casos novos na sua lista.",
  mailSyncAuth: "A permissão para ler seu e-mail expirou ou foi revogada. Reconecte sua caixa.",
  mailSyncFailed: "Não foi possível buscar o e-mail novo. Tente de novo em instantes.",
  mailSyncBackground: "Continua baixando em segundo plano; sua lista vai se atualizar sozinha.",
  mailSyncReconnect: "Reconectar e-mail",
  topTitle: "Suas 10 pendências principais",
  topSubtitle: "A Donexto já leu seu e-mail. Isto é o que vale resolver primeiro.",
  topRuleNote: "Ordenado por regras: urgência, prazo e importância (sem IA).",
  topEmpty: "Nenhuma pendência aberta. Você está em dia!",
  topOpen: "Abrir",
  topNoDue: "Sem prazo",
  topDue: "Vence {date}",
  topOverdue: "Venceu {date}",
  topDismiss: "Entendi",
  topLater: "Você pode vê-las de novo em Hoje › «Ver minhas 10 pendências».",
  topCta: "Ver minhas 10 pendências",
  topReasonOverdue: "Atrasado",
  topReasonToday: "Vence hoje",
  topReasonTomorrow: "Vence amanhã",
  topReasonWeek: "Esta semana",
  topReasonSecurity: "Segurança",
  topReasonMoney: "Dinheiro",
  topReasonPriority: "Importante",
  topReasonRecent: "Recente",
  statusNew: "Novo",
  statusAnalyzing: "Analisando",
  statusInProgress: "Em andamento",
  statusWaiting: "Aguardando",
  statusDelegated: "Delegado",
  statusResolved: "Feito",
  statusClosed: "Fechado",
  subjectLabel: "Assunto original",
  headlineNote: "Explicação automática por regras; o assunto original está abaixo.",
  askHelpTitle: "Como fazer na Donexto",
  askCasesTitle: "Nos seus casos",
  guideDragHint: "Arraste-me sobre qualquer opção e eu explico. Teclado: setas me movem, Home me devolve ao lugar.",
  guideNothing: "Nada para explicar aqui. Solte-me sobre um botão, um cartão ou uma área.",
  urgentHigh: "Urgente",
  urgentMed: "Em breve",
  urgentLow: "Quando puder",
  noDue: "Sem prazo",
  reconciled: "Conciliado",
  youQuestion: "Foi você?",
  monthMoves: "{count} movimentos",
  activeSubs: "{count} ativas",
  guideName: "Nexto · guia",
  close: "Fechar",
  menu: "Menu",
  alertsEmpty: "Não há alertas abertos.",
  doneSaved: "Caso marcado como feito.",
  caseReopen: "Reabrir",
  caseReopened: "Caso reaberto.",
  caseUndo: "Desfazer",
  caseRetry: "Tentar de novo",
  caseErrDone: "Não foi possível marcar como feito.",
  caseErrSnooze: "Não foi possível adiar.",
  caseErrReopen: "Não foi possível reabrir.",
  caseErrLocked: "O servidor pausou as alterações para manutenção; seu caso não mudou.",
  caseErrSession: "Sua sessão expirou. Entre de novo e tente outra vez.",
  caseErrMissing: "Esse caso não existe mais ou não é seu.",
  caseErrInvalid: "O horário escolhido não é válido.",
  caseErrNetwork: "Sem conexão com a Donexto. Verifique sua internet.",
  caseErrGeneric: "Algo falhou no servidor. Tente de novo.",
  actionFallback: "Revise este e-mail e escolha o próximo passo.",
  previewBadge: "Prévia de design · dados de exemplo",
  captionsLive: "Legendas",
  helpAsk: "Escreva ou dite uma pergunta. A Donexto busca nos seus casos e e-mails, sem um modelo pago.",
  helpDoNow: "O e-mail mais urgente, por prazo e prioridade.",
  helpAreas: "Cada e-mail cai numa área da vida.",
  helpMonth: "Movimentos identificados no e-mail. Não é um saldo.",
  helpGuide: "O Nexto explica a opção sob o cursor ou o foco.",
  helpSound: "Toca o tom do robô. A maioria dos navegadores ignora este arquivo como som do sistema.",
  saved: "Salvo na sua conta",
  errorGeneric: "Não foi possível concluir a ação.",
  personal: "Pessoal",
  connectedNow: "Online",
  dueIn: "Vence {when}",
  overdue: "Vencido",
  openAll: "Ver todos",
  statusOpen: "Aberto",
  mailReadOnly: "A caixa é lida; a Donexto não envia nem apaga e-mails.",
  rulePlaceholder: "Exemplo: contas de luz",
  onboardingPlatform: "Detectado: {platform}",
  installed: "Instalada na Tela de Início",
  notInstalled: "Aberta no navegador",
  allowAndTest: "Ativar e testar",
  flashLive: "Novo alerta da Donexto",
  noAmount: "Sem valor no e-mail",
  ordersEmpty: "Não há pedidos no seu e-mail.",
  subsEmpty: "Nenhuma assinatura identificada.",
  moneyEmpty: "Nenhum movimento de dinheiro no seu e-mail.",
  sourcesCount: "{count} e-mails",
  keyboardHelp: "Atalhos de teclado",
  actionToday: "Requer ação hoje",
  actionTodayEmpty: "Nada urgente hoje. Avisamos se algo chegar ao seu e-mail.",
  upcomingTitle: "Próximos vencimentos",
  upcomingNote: "Próximos 7 dias",
  upcomingEmpty: "Nenhum vencimento nos próximos 7 dias.",
  dayToday: "Hoje",
  dayTomorrow: "Amanhã",
  dayOverdue: "Vencido",
  alertsRecent: "Alertas recentes",
  alertsRecentEmpty: "Sem alertas nos últimos 7 dias.",
  alertWhySecurity: "Segurança",
  alertWhyPriority: "Prioridade alta",
  alertWhyPrice: "Preço subiu",
  alertWhyRule: "Sua regra",
  alertWhyPush: "Aviso",
  areasHint: "Toque uma área para filtrar",
  areaOpen: "{count} abertos",
  areaNone: "Nada pendente",
  areaNext: "Próximo: {when}",
  areaDueSoon: "{count} vencem em 7 dias",
  moneyTile: "{count} movimentos identificados no seu e-mail",
  moneyTileEmpty: "Nenhum movimento identificado no seu e-mail",
  moneyNotBalance: "Não é saldo nem extrato bancário",
  ordersTransit: "{count} a caminho",
  ordersDelivered: "{count} entregues",
  orderConfirmed: "Confirmado",
  orderShipped: "Enviado",
  orderDelivered: "Entregue",
  orderCancelled: "Cancelado",
  orderRefunded: "Reembolsado",
  subsRenew: "{count} renovam em 7 dias",
  subsIncrease: "{count} subiram de preço",
  healthInfo: "Apenas informativo · não é diagnóstico",
  askLocalNote: "Pesquisei nos seus casos, aqui mesmo, sem IA paga.",
  askFilters: "Filtrado por: {filters}",
  askTimeToday: "hoje",
  askTimeTomorrow: "amanhã",
  askTimeWeek: "próximos 7 dias",
  askTimeOverdue: "vencidos",
  askTimeMonth: "este mês",
  askStatusOpen: "pendentes",
  askStatusDone: "resolvidos",
  askCount: "{count} resultados",
  askCountOne: "1 resultado",
  moreCount: "+{count} mais",
  viewAll: "Ver tudo",
  clearFilter: "Remover filtro",
  areaMoney: "Dinheiro",
  areaOrders: "Pedidos",
  areaSubscriptions: "Assinaturas",
  areaWork: "Trabalho e negócios",
  areaHome: "Casa e família",
  areaHealth: "Saúde",
  areaBills: "Faturas e vencimentos",
  areaTravel: "Viagens",
  areaSecurity: "Segurança",
  areaGovernment: "Governo e impostos",
  areaInsurance: "Seguros",
  areaEducation: "Educação",
  areaSocial: "Social",
  areaEvents: "Eventos",
  areaPromos: "Promoções",
  areaOther: "Outros",
  commandCenter: "Central de comando",
};

const packs: Record<AppLanguage, Record<NxKey, string>> = {
  es,
  en,
  fr,
  it,
  pt,
};

export function nx(
  language: AppLanguage,
  key: NxKey,
  vars?: Record<string, string | number>,
): string {
  const template = packs[language][key] ?? packs.es[key];
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, name: string) =>
    vars[name] === undefined ? "" : String(vars[name]),
  );
}

export const ALERT_PHRASE: Record<AppLanguage, string> = {
  es: "Nueva alerta de Donexto",
  en: "New Donexto alert",
  fr: "Nouvelle alerte Donexto",
  it: "Nuovo avviso Donexto",
  pt: "Novo alerta da Donexto",
};
