from __future__ import annotations


def _entry(name: str, region: str, country: str) -> dict[str, str]:
    return {"name": name, "region": region, "country": country, "vertical": "bank"}


def _add(
    directory: dict[str, dict[str, str]],
    name: str,
    region: str,
    country: str,
    *domains: str,
) -> None:
    meta = _entry(name, region, country)
    for domain in domains:
        directory[domain.lower().strip()] = meta


BANKS: dict[str, dict[str, str]] = {}

# —— México (prioridad de producto) ——
_add(BANKS, "Citibanamex / Banamex", "MX", "MX", "citibanamex.com", "banamex.com", "banamex.com.mx")
_add(BANKS, "BBVA México", "MX", "MX", "bbva.mx", "bbva.com.mx")
_add(BANKS, "Banorte", "MX", "MX", "banorte.com", "banorte.com.mx")
_add(BANKS, "Santander México", "MX", "MX", "santander.com.mx")
_add(BANKS, "HSBC México", "MX", "MX", "hsbc.com.mx")
_add(BANKS, "Scotiabank México", "MX", "MX", "scotiabank.com.mx")
_add(BANKS, "Inbursa", "MX", "MX", "inbursa.com", "inbursa.com.mx")
_add(BANKS, "Banco Azteca", "MX", "MX", "bancoazteca.com.mx", "bancoazteca.com")
_add(BANKS, "BanCoppel", "MX", "MX", "bancoppel.com")
_add(BANKS, "Afirme", "MX", "MX", "afirme.com")
_add(BANKS, "Banregio", "MX", "MX", "banregio.com")
_add(BANKS, "BanBajío", "MX", "MX", "bb.com.mx", "banbajio.com")
_add(BANKS, "Ve por Más", "MX", "MX", "vepormas.com")
_add(BANKS, "Banca Mifel", "MX", "MX", "mifel.com.mx")
_add(BANKS, "Multiva", "MX", "MX", "multiva.com.mx", "multiva.com")
_add(BANKS, "Invex", "MX", "MX", "invex.com", "invex.com.mx")
_add(BANKS, "Monex", "MX", "MX", "monex.com.mx", "monex.com")
_add(BANKS, "Compartamos", "MX", "MX", "compartamos.com")
_add(BANKS, "CIBanco", "MX", "MX", "cibanco.com")
_add(BANKS, "Banco BASE", "MX", "MX", "bancobase.com")
_add(BANKS, "Actinver", "MX", "MX", "actinver.com")
_add(BANKS, "Hey Banco", "MX", "MX", "heybanco.com", "hey.inc")
_add(BANKS, "Openbank México", "MX", "MX", "openbank.mx")
_add(BANKS, "Nu México", "MX", "MX", "nu.com.mx", "nubank.com.mx")
_add(BANKS, "Mercado Pago México", "MX", "MX", "mercadopago.com.mx")
_add(BANKS, "American Express México", "MX", "MX", "americanexpress.com.mx")
_add(BANKS, "Clip", "MX", "MX", "clip.mx")
_add(BANKS, "STP", "MX", "MX", "stpmex.com")
_add(BANKS, "Banxico", "MX", "MX", "banxico.org.mx")
_add(BANKS, "Condusef", "MX", "MX", "condusef.gob.mx")
_add(BANKS, "CNBV", "MX", "MX", "cnbv.gob.mx")
_add(BANKS, "Klar", "MX", "MX", "klar.mx")
_add(BANKS, "Stori", "MX", "MX", "stori.mx", "storicard.com")
_add(BANKS, "Ualá México", "MX", "MX", "uala.com.mx")
_add(BANKS, "Fondeadora / Premia", "MX", "MX", "spinbyoxxo.com", "spin.com.mx")
_add(BANKS, "Banjercito", "MX", "MX", "banjercito.com.mx")
_add(BANKS, "Banco del Bienestar", "MX", "MX", "bancodelbienestar.gob.mx")
_add(BANKS, "Nafin", "MX", "MX", "nafin.com")
_add(BANKS, "Bancomext", "MX", "MX", "bancomext.com")
_add(BANKS, "Hipotecaria Nacional", "MX", "MX", "shf.gob.mx")

# —— Estados Unidos ——
_add(BANKS, "Chase", "US", "US", "chase.com", "jpmchase.com", "jpmorgan.com", "jpmorganchase.com")
_add(BANKS, "Bank of America", "US", "US", "bankofamerica.com", "bofa.com", "ml.com")
_add(BANKS, "Wells Fargo", "US", "US", "wellsfargo.com", "wellsfargoadvisors.com")
_add(BANKS, "Citibank", "US", "US", "citi.com", "citibank.com", "citicards.com", "citigroup.com")
_add(BANKS, "Capital One", "US", "US", "capitalone.com")
_add(BANKS, "U.S. Bank", "US", "US", "usbank.com")
_add(BANKS, "PNC", "US", "US", "pnc.com")
_add(BANKS, "TD Bank", "US", "US", "tdbank.com")
_add(BANKS, "Truist", "US", "US", "truist.com")
_add(BANKS, "Citizens", "US", "US", "citizensbank.com")
_add(BANKS, "Fifth Third", "US", "US", "53.com")
_add(BANKS, "Ally", "US", "US", "ally.com")
_add(BANKS, "Discover", "US", "US", "discover.com")
_add(BANKS, "American Express", "US", "US", "americanexpress.com", "aexp.com", "amex.com")
_add(BANKS, "USAA", "US", "US", "usaa.com")
_add(BANKS, "Navy Federal", "US", "US", "navyfederal.org")
_add(BANKS, "Charles Schwab", "US", "US", "schwab.com")
_add(BANKS, "Fidelity", "US", "US", "fidelity.com", "fidelityinvestments.com")
_add(BANKS, "Vanguard", "US", "US", "vanguard.com")
_add(BANKS, "Goldman Sachs / Marcus", "US", "US", "goldmansachs.com", "marcus.com")
_add(BANKS, "SoFi", "US", "US", "sofi.com")
_add(BANKS, "Chime", "US", "US", "chime.com")
_add(BANKS, "Varo", "US", "US", "varo.com")
_add(BANKS, "Cash App", "US", "US", "cash.app", "cashapp.com", "square.com", "squareup.com")
_add(BANKS, "Venmo", "US", "US", "venmo.com")
_add(BANKS, "PayPal", "US", "US", "paypal.com", "paypal.me")
_add(BANKS, "Stripe", "US", "US", "stripe.com")
_add(BANKS, "Regions", "US", "US", "regions.com")
_add(BANKS, "Huntington", "US", "US", "huntington.com")
_add(BANKS, "KeyBank", "US", "US", "key.com")
_add(BANKS, "M&T Bank", "US", "US", "mtb.com", "mtb.bank")
_add(BANKS, "BMO Harris", "US", "US", "bmoharris.com")
_add(BANKS, "HSBC US", "US", "US", "us.hsbc.com")
_add(BANKS, "American Express Delta", "US", "US", "deltaamex.com")
_add(BANKS, "Synchrony", "US", "US", "synchrony.com", "synchronybank.com")
_add(BANKS, "Barclays US", "US", "US", "barclaycardus.com")
_add(BANKS, "Citi ThankYou", "US", "US", "thankyou.com")
_add(BANKS, "Apple Card / Goldman", "US", "US", "applecard.apple")
_add(BANKS, "Affirm", "US", "US", "affirm.com")
_add(BANKS, "Klarna", "US", "US", "klarna.com")
_add(BANKS, "Afterpay", "US", "US", "afterpay.com")
_add(BANKS, "Bread / Alliance Data", "US", "US", "breadpayments.com")
_add(BANKS, "Western Union", "US", "US", "westernunion.com")
_add(BANKS, "MoneyGram", "US", "US", "moneygram.com")
_add(BANKS, "Wise", "GLOBAL", "GB", "wise.com", "transferwise.com")
_add(BANKS, "Visa", "GLOBAL", "US", "visa.com")
_add(BANKS, "Mastercard", "GLOBAL", "US", "mastercard.com")

# —— Canadá (cobertura lista; el producto aún no entra) ——
_add(BANKS, "RBC", "CA", "CA", "rbc.com", "royalbank.com", "rbcroyalbank.com")
_add(BANKS, "TD Canada Trust", "CA", "CA", "td.com", "tdcanadatrust.com")
_add(BANKS, "Scotiabank", "CA", "CA", "scotiabank.com")
_add(BANKS, "BMO", "CA", "CA", "bmo.com")
_add(BANKS, "CIBC", "CA", "CA", "cibc.com")
_add(BANKS, "National Bank of Canada", "CA", "CA", "nbc.ca", "bnc.ca")
_add(BANKS, "Desjardins", "CA", "CA", "desjardins.com")
_add(BANKS, "Tangerine", "CA", "CA", "tangerine.ca")
_add(BANKS, "EQ Bank", "CA", "CA", "eqbank.ca")
_add(BANKS, "Simplii", "CA", "CA", "simplii.com")
_add(BANKS, "Laurentian Bank", "CA", "CA", "laurentianbank.ca")
_add(BANKS, "ATB", "CA", "CA", "atb.com")
_add(BANKS, "Vancity", "CA", "CA", "vancity.com")
_add(BANKS, "PC Financial", "CA", "CA", "pcfinancial.ca")
_add(BANKS, "Koho", "CA", "CA", "koho.ca")
_add(BANKS, "Wealthsimple", "CA", "CA", "wealthsimple.com")

# —— Unión Europea / Reino Unido ——
_add(BANKS, "Santander España", "EU", "ES", "santander.es", "bancosantander.es")
_add(BANKS, "BBVA España", "EU", "ES", "bbva.es", "bbva.com")
_add(BANKS, "CaixaBank", "EU", "ES", "caixabank.es", "caixabank.com")
_add(BANKS, "Banco Sabadell", "EU", "ES", "bancsabadell.com", "sabadell.com")
_add(BANKS, "Bankinter", "EU", "ES", "bankinter.com")
_add(BANKS, "ING", "EU", "NL", "ing.com", "ing.es", "ing.nl", "ing.de", "ing.fr")
_add(BANKS, "Deutsche Bank", "EU", "DE", "db.com", "deutsche-bank.de", "deutschebank.com")
_add(BANKS, "Commerzbank", "EU", "DE", "commerzbank.com", "commerzbank.de")
_add(BANKS, "Sparkasse", "EU", "DE", "sparkasse.de")
_add(BANKS, "BNP Paribas", "EU", "FR", "bnpparibas.com", "bnpparibas.es", "bnpparibas.net")
_add(BANKS, "Société Générale", "EU", "FR", "societegenerale.com", "societegenerale.fr")
_add(BANKS, "Crédit Agricole", "EU", "FR", "credit-agricole.com", "credit-agricole.fr")
_add(BANKS, "Crédit Mutuel", "EU", "FR", "creditmutuel.fr")
_add(BANKS, "La Banque Postale", "EU", "FR", "labanquepostale.fr")
_add(BANKS, "Intesa Sanpaolo", "EU", "IT", "intesasanpaolo.com")
_add(BANKS, "UniCredit", "EU", "IT", "unicredit.it", "unicredit.eu")
_add(BANKS, "Barclays", "EU", "GB", "barclays.co.uk", "barclays.com")
_add(BANKS, "HSBC UK", "EU", "GB", "hsbc.co.uk")
_add(BANKS, "Lloyds", "EU", "GB", "lloydsbank.com", "lloydsbankinggroup.com")
_add(BANKS, "NatWest", "EU", "GB", "natwest.com", "natwest.co.uk")
_add(BANKS, "RBS", "EU", "GB", "rbs.co.uk")
_add(BANKS, "Nationwide", "EU", "GB", "nationwide.co.uk")
_add(BANKS, "Santander UK", "EU", "GB", "santander.co.uk")
_add(BANKS, "Halifax", "EU", "GB", "halifax.co.uk")
_add(BANKS, "Rabobank", "EU", "NL", "rabobank.com", "rabobank.nl")
_add(BANKS, "ABN AMRO", "EU", "NL", "abnamro.com", "abnamro.nl")
_add(BANKS, "Nordea", "EU", "SE", "nordea.com", "nordea.se", "nordea.fi", "nordea.dk")
_add(BANKS, "SEB", "EU", "SE", "seb.se", "seb.com")
_add(BANKS, "Handelsbanken", "EU", "SE", "handelsbanken.com", "handelsbanken.se")
_add(BANKS, "Danske Bank", "EU", "DK", "danskebank.com", "danskebank.dk")
_add(BANKS, "DNB", "EU", "NO", "dnb.no")
_add(BANKS, "Revolut", "EU", "GB", "revolut.com")
_add(BANKS, "N26", "EU", "DE", "n26.com")
_add(BANKS, "Monzo", "EU", "GB", "monzo.com")
_add(BANKS, "Starling", "EU", "GB", "starlingbank.com")
_add(BANKS, "Bunq", "EU", "NL", "bunq.com")
_add(BANKS, "KBC", "EU", "BE", "kbc.be", "kbc.com")
_add(BANKS, "Belfius", "EU", "BE", "belfius.be")
_add(BANKS, "UBS", "EU", "CH", "ubs.com")
_add(BANKS, "PostFinance", "EU", "CH", "postfinance.ch")
_add(BANKS, "Erste", "EU", "AT", "erstegroup.com", "sparkasse.at")
_add(BANKS, "Raiffeisen", "EU", "AT", "raiffeisen.at")
_add(BANKS, "Millennium bcp", "EU", "PT", "millenniumbcp.pt")
_add(BANKS, "Caixa Geral", "EU", "PT", "cgd.pt")
_add(BANKS, "PKO Bank Polski", "EU", "PL", "pkobp.pl")
_add(BANKS, "mBank", "EU", "PL", "mbank.pl")

# —— Latinoamérica (fuera de MX) ——
_add(BANKS, "Bancolombia", "LATAM", "CO", "bancolombia.com", "bancolombia.com.co")
_add(BANKS, "Davivienda", "LATAM", "CO", "davivienda.com")
_add(BANKS, "Banco de Bogotá", "LATAM", "CO", "bancodebogota.com")
_add(BANKS, "BBVA Colombia", "LATAM", "CO", "bbva.com.co")
_add(BANKS, "Nequi", "LATAM", "CO", "nequi.com.co")
_add(BANKS, "Banco de Chile", "LATAM", "CL", "bancochile.cl")
_add(BANKS, "BCI", "LATAM", "CL", "bci.cl")
_add(BANKS, "Santander Chile", "LATAM", "CL", "santander.cl")
_add(BANKS, "Banco Estado", "LATAM", "CL", "bancoestado.cl")
_add(BANKS, "Itaú Chile", "LATAM", "CL", "itau.cl")
_add(BANKS, "Banco Galicia", "LATAM", "AR", "galingalicia.com", "bancogalicia.com", "galicia.ar")
_add(BANKS, "Banco Macro", "LATAM", "AR", "macro.com.ar")
_add(BANKS, "Santander Argentina", "LATAM", "AR", "santander.com.ar")
_add(BANKS, "BBVA Argentina", "LATAM", "AR", "bbva.com.ar")
_add(BANKS, "Ualá", "LATAM", "AR", "uala.com.ar")
_add(BANKS, "Mercado Pago", "LATAM", "AR", "mercadopago.com", "mercadopago.com.ar")
_add(BANKS, "Itaú", "LATAM", "BR", "itau.com.br")
_add(BANKS, "Bradesco", "LATAM", "BR", "bradesco.com.br")
_add(BANKS, "Banco do Brasil", "LATAM", "BR", "bb.com.br")
_add(BANKS, "Caixa Econômica", "LATAM", "BR", "caixa.gov.br")
_add(BANKS, "Santander Brasil", "LATAM", "BR", "santander.com.br")
_add(BANKS, "Nubank", "LATAM", "BR", "nubank.com.br", "nu.com.br")
_add(BANKS, "Inter", "LATAM", "BR", "bancointer.com.br")
_add(BANKS, "C6 Bank", "LATAM", "BR", "c6bank.com.br")
_add(BANKS, "PicPay", "LATAM", "BR", "picpay.com")
_add(BANKS, "BCP", "LATAM", "PE", "viabcp.com")
_add(BANKS, "Interbank", "LATAM", "PE", "interbank.pe")
_add(BANKS, "BBVA Perú", "LATAM", "PE", "bbva.pe")
_add(BANKS, "Scotiabank Perú", "LATAM", "PE", "scotiabank.com.pe")
_add(BANKS, "Banco Pichincha", "LATAM", "EC", "pichincha.com")
_add(BANKS, "Banco Guayaquil", "LATAM", "EC", "bancoguayaquil.com")
_add(BANKS, "Banesco", "LATAM", "VE", "banesco.com")
_add(BANKS, "Mercantil", "LATAM", "VE", "mercantilbanco.com")
_add(BANKS, "Banrural", "LATAM", "GT", "banrural.com.gt")
_add(BANKS, "Banco Industrial", "LATAM", "GT", "bi.com.gt")
_add(BANKS, "BAC Credomatic", "LATAM", "CR", "baccredomatic.com", "bac.net")
_add(BANKS, "Banreservas", "LATAM", "DO", "banreservas.com")
_add(BANKS, "Banco Popular Dominicano", "LATAM", "DO", "popularenlinea.com")
_add(BANKS, "Banco General", "LATAM", "PA", "bgeneral.com")
_add(BANKS, "Banistmo", "LATAM", "PA", "banistmo.com")
_add(BANKS, "Banco Nacional de Costa Rica", "LATAM", "CR", "bncr.fi.cr")
_add(BANKS, "Banco Agrícola", "LATAM", "SV", "bancoagricola.com")
_add(BANKS, "Ficohsa", "LATAM", "HN", "ficohsa.com")
_add(BANKS, "Promerica", "LATAM", "GT", "promerica.gt", "promerica.com")
